# Generated by Django 4.2.13 on 2024-06-22 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sivaria", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userhasparent",
            name="phone_parent_1",
        ),
        migrations.RemoveField(
            model_name="userhasparent",
            name="phone_parent_2",
        ),
        migrations.AddField(
            model_name="userhasparent",
            name="email_parent_1",
            field=models.EmailField(
                default=None, max_length=254, null=True, unique=True
            ),
        ),
        migrations.AddField(
            model_name="userhasparent",
            name="email_parent_2",
            field=models.EmailField(
                default=None, max_length=254, null=True, unique=True
            ),
        ),
    ]
