# Generated by Django 4.2.13 on 2024-06-27 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sivaria", "0003_appuser_expo_token_alter_appuser_phone"),
    ]

    operations = [
        migrations.CreateModel(
            name="PushNotificationType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.CharField(max_length=20, unique=True)),
                ("title", models.TextField(max_length=50)),
                ("body", models.TextField(max_length=255)),
                ("data", models.TextField(default=None, max_length=255, null=True)),
            ],
        ),
    ]
