# Generated by Django 4.2.13 on 2024-06-27 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sivaria", "0004_pushnotificationtype"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pushnotificationtype",
            name="data",
            field=models.TextField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
