# Generated by Django 4.2.13 on 2024-07-01 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sivaria", "0006_alter_appuser_options_alter_appuser_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appuser",
            name="username",
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
