# Generated by Django 4.2.13 on 2024-07-02 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sivaria", "0007_alter_appuser_username"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="appuser",
            options={"verbose_name": "user", "verbose_name_plural": "users"},
        ),
        migrations.AlterUniqueTogether(
            name="appuser",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="userhasparent",
            name="email_parent_1",
            field=models.EmailField(default=None, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name="userhasparent",
            name="email_parent_2",
            field=models.EmailField(default=None, max_length=254, null=True),
        ),
    ]
