# Generated by Django 4.2.13 on 2024-07-13 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "sivaria",
            "0008_alter_appuser_options_alter_appuser_unique_together_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=10)),
                ("subject", models.CharField(max_length=80)),
                ("message", models.TextField(max_length=255)),
            ],
        ),
    ]
