# Generated by Django 4.2.13 on 2024-07-13 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sivaria", "0009_emailtemplate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userhasparent",
            name="email_parent_1",
            field=models.EmailField(
                blank=True, default=None, max_length=254, null=True
            ),
        ),
        migrations.AlterField(
            model_name="userhasparent",
            name="email_parent_2",
            field=models.EmailField(
                blank=True, default=None, max_length=254, null=True
            ),
        ),
    ]
