# Generated by Django 4.2.13 on 2024-07-14 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sivaria", "0010_alter_userhasparent_email_parent_1_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emailtemplate",
            name="code",
            field=models.CharField(max_length=20),
        ),
    ]
