# Generated by Django 4.2.13 on 2024-07-14 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sivaria", "0011_alter_emailtemplate_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emailtemplate",
            name="message",
            field=models.TextField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
