# Generated by Django 4.2.13 on 2024-07-14 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sivaria", "0013_alter_emailtemplate_code_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pushnotificationtype",
            name="body",
            field=models.TextField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
