# Generated by Django 4.2.13 on 2024-07-14 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sivaria", "0014_alter_pushnotificationtype_body"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pushnotificationtype",
            name="title",
            field=models.CharField(max_length=80),
        ),
    ]
