# Generated by Django 4.2.13 on 2024-07-16 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sivaria", "0015_alter_pushnotificationtype_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emailtemplate",
            name="message",
            field=models.TextField(blank=True, default=None, max_length=512, null=True),
        ),
    ]
