# Generated by Django 4.2.13 on 2024-07-21 19:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("sivaria", "0016_alter_emailtemplate_message"),
    ]

    operations = [
        migrations.CreateModel(
            name="SOCIAL_DATA",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=20)),
                ("date", models.DateTimeField(blank=True, default=None, null=True)),
                (
                    "course",
                    models.CharField(
                        blank=True, default=None, max_length=30, null=True
                    ),
                ),
                ("age", models.IntegerField(blank=True, default=None, null=True)),
                (
                    "gender",
                    models.CharField(
                        blank=True, default=None, max_length=30, null=True
                    ),
                ),
                (
                    "trans",
                    models.CharField(
                        blank=True, default=None, max_length=10, null=True
                    ),
                ),
                (
                    "job_situation_father",
                    models.CharField(
                        blank=True, default=None, max_length=30, null=True
                    ),
                ),
                (
                    "job_situation_mother",
                    models.CharField(
                        blank=True, default=None, max_length=30, null=True
                    ),
                ),
                (
                    "academic_level_father",
                    models.CharField(
                        blank=True, default=None, max_length=30, null=True
                    ),
                ),
                (
                    "academic_level_mother",
                    models.CharField(
                        blank=True, default=None, max_length=30, null=True
                    ),
                ),
                (
                    "academic_performance",
                    models.CharField(
                        blank=True, default=None, max_length=30, null=True
                    ),
                ),
                (
                    "previous_psychiatric_treatment",
                    models.IntegerField(blank=True, default=None, null=True),
                ),
                (
                    "chronic_disease",
                    models.IntegerField(blank=True, default=None, null=True),
                ),
                (
                    "female_self_perception",
                    models.IntegerField(blank=True, default=None, null=True),
                ),
                (
                    "male_self_perception",
                    models.IntegerField(blank=True, default=None, null=True),
                ),
                (
                    "female_others_perception",
                    models.IntegerField(blank=True, default=None, null=True),
                ),
                (
                    "male_others_perception",
                    models.IntegerField(blank=True, default=None, null=True),
                ),
                ("weight", models.FloatField(blank=True, default=None, null=True)),
                ("height", models.FloatField(blank=True, default=None, null=True)),
                (
                    "discrimination_type",
                    models.CharField(
                        blank=True, default=None, max_length=30, null=True
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SENA",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=20)),
                ("date", models.DateTimeField(blank=True, default=None, null=True)),
                ("sena19", models.IntegerField(blank=True, default=None, null=True)),
                ("sena23", models.IntegerField(blank=True, default=None, null=True)),
                ("sena69", models.IntegerField(blank=True, default=None, null=True)),
                ("sena99", models.IntegerField(blank=True, default=None, null=True)),
                ("sena103", models.IntegerField(blank=True, default=None, null=True)),
                ("sena111", models.IntegerField(blank=True, default=None, null=True)),
                ("sena112", models.IntegerField(blank=True, default=None, null=True)),
                ("sena115", models.IntegerField(blank=True, default=None, null=True)),
                ("sena117", models.IntegerField(blank=True, default=None, null=True)),
                ("sena129", models.IntegerField(blank=True, default=None, null=True)),
                ("sena137", models.IntegerField(blank=True, default=None, null=True)),
                ("sena139", models.IntegerField(blank=True, default=None, null=True)),
                ("sena141", models.IntegerField(blank=True, default=None, null=True)),
                ("sena146", models.IntegerField(blank=True, default=None, null=True)),
                ("sena150", models.IntegerField(blank=True, default=None, null=True)),
                ("sena188", models.IntegerField(blank=True, default=None, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RRSS",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=20)),
                ("date", models.DateTimeField(blank=True, default=None, null=True)),
                ("rrss1", models.IntegerField(blank=True, default=None, null=True)),
                ("rrss2", models.IntegerField(blank=True, default=None, null=True)),
                ("rrss3", models.IntegerField(blank=True, default=None, null=True)),
                ("rrss4", models.IntegerField(blank=True, default=None, null=True)),
                ("rrss5", models.IntegerField(blank=True, default=None, null=True)),
                ("rrss6", models.IntegerField(blank=True, default=None, null=True)),
                ("rrss7", models.IntegerField(blank=True, default=None, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PARQ",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=20)),
                ("date", models.DateTimeField(blank=True, default=None, null=True)),
                ("parq1", models.IntegerField(blank=True, default=None, null=True)),
                ("parq2", models.IntegerField(blank=True, default=None, null=True)),
                ("parq3", models.IntegerField(blank=True, default=None, null=True)),
                ("parq4", models.IntegerField(blank=True, default=None, null=True)),
                ("parq5", models.IntegerField(blank=True, default=None, null=True)),
                ("parq6", models.IntegerField(blank=True, default=None, null=True)),
                ("parq7", models.IntegerField(blank=True, default=None, null=True)),
                ("parq8", models.IntegerField(blank=True, default=None, null=True)),
                ("parq9", models.IntegerField(blank=True, default=None, null=True)),
                ("parq10", models.IntegerField(blank=True, default=None, null=True)),
                ("parq11", models.IntegerField(blank=True, default=None, null=True)),
                ("parq12", models.IntegerField(blank=True, default=None, null=True)),
                ("parq13", models.IntegerField(blank=True, default=None, null=True)),
                ("parq14", models.IntegerField(blank=True, default=None, null=True)),
                ("parq15", models.IntegerField(blank=True, default=None, null=True)),
                ("parq16", models.IntegerField(blank=True, default=None, null=True)),
                ("parq17", models.IntegerField(blank=True, default=None, null=True)),
                ("parq18", models.IntegerField(blank=True, default=None, null=True)),
                ("parq19", models.IntegerField(blank=True, default=None, null=True)),
                ("parq20", models.IntegerField(blank=True, default=None, null=True)),
                ("parq21", models.IntegerField(blank=True, default=None, null=True)),
                ("parq22", models.IntegerField(blank=True, default=None, null=True)),
                ("parq23", models.IntegerField(blank=True, default=None, null=True)),
                ("parq24", models.IntegerField(blank=True, default=None, null=True)),
                ("parq25", models.IntegerField(blank=True, default=None, null=True)),
                ("parq26", models.IntegerField(blank=True, default=None, null=True)),
                ("parq27", models.IntegerField(blank=True, default=None, null=True)),
                ("parq28", models.IntegerField(blank=True, default=None, null=True)),
                ("parq29", models.IntegerField(blank=True, default=None, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MULTICAGE_CAD_4",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=20)),
                ("date", models.DateTimeField(blank=True, default=None, null=True)),
                ("mcad1", models.IntegerField(blank=True, default=None, null=True)),
                ("mcad2", models.IntegerField(blank=True, default=None, null=True)),
                ("mcad3", models.IntegerField(blank=True, default=None, null=True)),
                ("mcad4", models.IntegerField(blank=True, default=None, null=True)),
                ("mcad5", models.IntegerField(blank=True, default=None, null=True)),
                ("mcad6", models.IntegerField(blank=True, default=None, null=True)),
                ("mcad7", models.IntegerField(blank=True, default=None, null=True)),
                ("mcad8", models.IntegerField(blank=True, default=None, null=True)),
                ("mcad9", models.IntegerField(blank=True, default=None, null=True)),
                ("mcad10", models.IntegerField(blank=True, default=None, null=True)),
                ("mcad11", models.IntegerField(blank=True, default=None, null=True)),
                ("mcad12", models.IntegerField(blank=True, default=None, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="INQ",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=20)),
                ("date", models.DateTimeField(blank=True, default=None, null=True)),
                ("inq1", models.IntegerField(blank=True, default=None, null=True)),
                ("inq2", models.IntegerField(blank=True, default=None, null=True)),
                ("inq3", models.IntegerField(blank=True, default=None, null=True)),
                ("inq4", models.IntegerField(blank=True, default=None, null=True)),
                ("inq5", models.IntegerField(blank=True, default=None, null=True)),
                ("inq6", models.IntegerField(blank=True, default=None, null=True)),
                ("inq7", models.IntegerField(blank=True, default=None, null=True)),
                ("inq8", models.IntegerField(blank=True, default=None, null=True)),
                ("inq9", models.IntegerField(blank=True, default=None, null=True)),
                ("inq10", models.IntegerField(blank=True, default=None, null=True)),
                ("inq11", models.IntegerField(blank=True, default=None, null=True)),
                ("inq12", models.IntegerField(blank=True, default=None, null=True)),
                ("inq13", models.IntegerField(blank=True, default=None, null=True)),
                ("inq14", models.IntegerField(blank=True, default=None, null=True)),
                ("inq15", models.IntegerField(blank=True, default=None, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="INJURY",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=20)),
                ("date", models.DateTimeField(blank=True, default=None, null=True)),
                ("inq1", models.IntegerField(blank=True, default=None, null=True)),
                ("inq2", models.IntegerField(blank=True, default=None, null=True)),
                ("inq3", models.IntegerField(blank=True, default=None, null=True)),
                ("inq4", models.IntegerField(blank=True, default=None, null=True)),
                ("inq5", models.IntegerField(blank=True, default=None, null=True)),
                ("inq6", models.IntegerField(blank=True, default=None, null=True)),
                ("inq7", models.IntegerField(blank=True, default=None, null=True)),
                ("inq8", models.IntegerField(blank=True, default=None, null=True)),
                ("inq9", models.IntegerField(blank=True, default=None, null=True)),
                ("inq10", models.IntegerField(blank=True, default=None, null=True)),
                ("inq11", models.IntegerField(blank=True, default=None, null=True)),
                ("inq12", models.IntegerField(blank=True, default=None, null=True)),
                ("inq13", models.IntegerField(blank=True, default=None, null=True)),
                ("inq14", models.IntegerField(blank=True, default=None, null=True)),
                ("inq15", models.IntegerField(blank=True, default=None, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FAMILY",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=20)),
                ("date", models.DateTimeField(blank=True, default=None, null=True)),
                ("family1", models.IntegerField(blank=True, default=None, null=True)),
                ("family2", models.IntegerField(blank=True, default=None, null=True)),
                ("family3", models.IntegerField(blank=True, default=None, null=True)),
                ("family4", models.IntegerField(blank=True, default=None, null=True)),
                ("family5", models.IntegerField(blank=True, default=None, null=True)),
                ("family6", models.IntegerField(blank=True, default=None, null=True)),
                ("family7", models.IntegerField(blank=True, default=None, null=True)),
                ("family8", models.IntegerField(blank=True, default=None, null=True)),
                ("family9", models.IntegerField(blank=True, default=None, null=True)),
                ("family10", models.IntegerField(blank=True, default=None, null=True)),
                ("family11", models.IntegerField(blank=True, default=None, null=True)),
                ("family12", models.IntegerField(blank=True, default=None, null=True)),
                ("family13", models.IntegerField(blank=True, default=None, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ER",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=20)),
                ("date", models.DateTimeField(blank=True, default=None, null=True)),
                ("er1", models.IntegerField(blank=True, default=None, null=True)),
                ("er2", models.IntegerField(blank=True, default=None, null=True)),
                ("er3", models.IntegerField(blank=True, default=None, null=True)),
                ("er4", models.IntegerField(blank=True, default=None, null=True)),
                ("er5", models.IntegerField(blank=True, default=None, null=True)),
                ("er6", models.IntegerField(blank=True, default=None, null=True)),
                ("er7", models.IntegerField(blank=True, default=None, null=True)),
                ("er8", models.IntegerField(blank=True, default=None, null=True)),
                ("er9", models.IntegerField(blank=True, default=None, null=True)),
                ("er10", models.IntegerField(blank=True, default=None, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ED",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=20)),
                ("date", models.DateTimeField(blank=True, default=None, null=True)),
                ("ed1", models.IntegerField(blank=True, default=None, null=True)),
                ("ed2", models.IntegerField(blank=True, default=None, null=True)),
                ("ed3", models.IntegerField(blank=True, default=None, null=True)),
                ("ed4", models.IntegerField(blank=True, default=None, null=True)),
                ("ed5", models.IntegerField(blank=True, default=None, null=True)),
                ("ed6", models.IntegerField(blank=True, default=None, null=True)),
                ("ed7", models.IntegerField(blank=True, default=None, null=True)),
                ("ed8", models.IntegerField(blank=True, default=None, null=True)),
                ("ed9", models.IntegerField(blank=True, default=None, null=True)),
                ("ed10", models.IntegerField(blank=True, default=None, null=True)),
                ("ed11", models.IntegerField(blank=True, default=None, null=True)),
                ("ed12", models.IntegerField(blank=True, default=None, null=True)),
                ("ed13", models.IntegerField(blank=True, default=None, null=True)),
                ("ed14", models.IntegerField(blank=True, default=None, null=True)),
                ("ed15", models.IntegerField(blank=True, default=None, null=True)),
                ("ed16", models.IntegerField(blank=True, default=None, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EBIPQ_ECIPQ",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=20)),
                ("date", models.DateTimeField(blank=True, default=None, null=True)),
                ("vb1", models.IntegerField(blank=True, default=None, null=True)),
                ("vb2", models.IntegerField(blank=True, default=None, null=True)),
                ("vb4", models.IntegerField(blank=True, default=None, null=True)),
                ("ab1", models.IntegerField(blank=True, default=None, null=True)),
                ("ab2", models.IntegerField(blank=True, default=None, null=True)),
                ("ab4", models.IntegerField(blank=True, default=None, null=True)),
                ("cybv1", models.IntegerField(blank=True, default=None, null=True)),
                ("cybv2", models.IntegerField(blank=True, default=None, null=True)),
                ("cybv3", models.IntegerField(blank=True, default=None, null=True)),
                ("cybb1", models.IntegerField(blank=True, default=None, null=True)),
                ("cybb2", models.IntegerField(blank=True, default=None, null=True)),
                ("cybb3", models.IntegerField(blank=True, default=None, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CERQS",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=20)),
                ("date", models.DateTimeField(blank=True, default=None, null=True)),
                ("cerqs1", models.IntegerField(blank=True, default=None, null=True)),
                ("cerqs2", models.IntegerField(blank=True, default=None, null=True)),
                ("cerqs3", models.IntegerField(blank=True, default=None, null=True)),
                ("cerqs4", models.IntegerField(blank=True, default=None, null=True)),
                ("cerqs5", models.IntegerField(blank=True, default=None, null=True)),
                ("cerqs6", models.IntegerField(blank=True, default=None, null=True)),
                ("cerqs7", models.IntegerField(blank=True, default=None, null=True)),
                ("cerqs8", models.IntegerField(blank=True, default=None, null=True)),
                ("cerqs9", models.IntegerField(blank=True, default=None, null=True)),
                ("cerqs10", models.IntegerField(blank=True, default=None, null=True)),
                ("cerqs11", models.IntegerField(blank=True, default=None, null=True)),
                ("cerqs12", models.IntegerField(blank=True, default=None, null=True)),
                ("cerqs13", models.IntegerField(blank=True, default=None, null=True)),
                ("cerqs14", models.IntegerField(blank=True, default=None, null=True)),
                ("cerqs15", models.IntegerField(blank=True, default=None, null=True)),
                ("cerqs16", models.IntegerField(blank=True, default=None, null=True)),
                ("cerqs17", models.IntegerField(blank=True, default=None, null=True)),
                ("cerqs18", models.IntegerField(blank=True, default=None, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
