# Generated by Django 4.2.13 on 2024-07-21 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sivaria", "0017_social_data_sena_rrss_parq_multicage_cad_4_inq_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="family",
            name="family12",
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
