# Generated by Django 4.2.13 on 2024-07-23 19:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("sivaria", "0018_alter_family_family12"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cerqs",
            name="cerqs1",
            field=models.IntegerField(
                blank=True, default=None, max_length=1, null=True
            ),
        ),
        migrations.AlterField(
            model_name="cerqs",
            name="cerqs10",
            field=models.IntegerField(
                blank=True, default=None, max_length=1, null=True
            ),
        ),
        migrations.AlterField(
            model_name="cerqs",
            name="cerqs11",
            field=models.IntegerField(
                blank=True, default=None, max_length=1, null=True
            ),
        ),
        migrations.AlterField(
            model_name="cerqs",
            name="cerqs12",
            field=models.IntegerField(
                blank=True, default=None, max_length=1, null=True
            ),
        ),
        migrations.AlterField(
            model_name="cerqs",
            name="cerqs13",
            field=models.IntegerField(
                blank=True, default=None, max_length=1, null=True
            ),
        ),
        migrations.AlterField(
            model_name="cerqs",
            name="cerqs14",
            field=models.IntegerField(
                blank=True, default=None, max_length=1, null=True
            ),
        ),
        migrations.AlterField(
            model_name="cerqs",
            name="cerqs15",
            field=models.IntegerField(
                blank=True, default=None, max_length=1, null=True
            ),
        ),
        migrations.AlterField(
            model_name="cerqs",
            name="cerqs16",
            field=models.IntegerField(
                blank=True, default=None, max_length=1, null=True
            ),
        ),
        migrations.AlterField(
            model_name="cerqs",
            name="cerqs17",
            field=models.IntegerField(
                blank=True, default=None, max_length=1, null=True
            ),
        ),
        migrations.AlterField(
            model_name="cerqs",
            name="cerqs18",
            field=models.IntegerField(
                blank=True, default=None, max_length=1, null=True
            ),
        ),
        migrations.AlterField(
            model_name="cerqs",
            name="cerqs2",
            field=models.IntegerField(
                blank=True, default=None, max_length=1, null=True
            ),
        ),
        migrations.AlterField(
            model_name="cerqs",
            name="cerqs3",
            field=models.IntegerField(
                blank=True, default=None, max_length=1, null=True
            ),
        ),
        migrations.AlterField(
            model_name="cerqs",
            name="cerqs4",
            field=models.IntegerField(
                blank=True, default=None, max_length=1, null=True
            ),
        ),
        migrations.AlterField(
            model_name="cerqs",
            name="cerqs5",
            field=models.IntegerField(
                blank=True, default=None, max_length=1, null=True
            ),
        ),
        migrations.AlterField(
            model_name="cerqs",
            name="cerqs6",
            field=models.IntegerField(
                blank=True, default=None, max_length=1, null=True
            ),
        ),
        migrations.AlterField(
            model_name="cerqs",
            name="cerqs7",
            field=models.IntegerField(
                blank=True, default=None, max_length=1, null=True
            ),
        ),
        migrations.AlterField(
            model_name="cerqs",
            name="cerqs8",
            field=models.IntegerField(
                blank=True, default=None, max_length=1, null=True
            ),
        ),
        migrations.AlterField(
            model_name="cerqs",
            name="cerqs9",
            field=models.IntegerField(
                blank=True, default=None, max_length=1, null=True
            ),
        ),
        migrations.AlterField(
            model_name="ebipq_ecipq",
            name="ab1",
            field=models.IntegerField(
                blank=True, default=None, max_length=1, null=True
            ),
        ),
        migrations.AlterField(
            model_name="ebipq_ecipq",
            name="ab2",
            field=models.IntegerField(
                blank=True, default=None, max_length=1, null=True
            ),
        ),
        migrations.AlterField(
            model_name="ebipq_ecipq",
            name="ab4",
            field=models.IntegerField(
                blank=True, default=None, max_length=1, null=True
            ),
        ),
        migrations.AlterField(
            model_name="ebipq_ecipq",
            name="cybb1",
            field=models.IntegerField(
                blank=True, default=None, max_length=1, null=True
            ),
        ),
        migrations.AlterField(
            model_name="ebipq_ecipq",
            name="cybb2",
            field=models.IntegerField(
                blank=True, default=None, max_length=1, null=True
            ),
        ),
        migrations.AlterField(
            model_name="ebipq_ecipq",
            name="cybb3",
            field=models.IntegerField(
                blank=True, default=None, max_length=1, null=True
            ),
        ),
        migrations.AlterField(
            model_name="ebipq_ecipq",
            name="cybv1",
            field=models.IntegerField(
                blank=True, default=None, max_length=1, null=True
            ),
        ),
        migrations.AlterField(
            model_name="ebipq_ecipq",
            name="cybv2",
            field=models.IntegerField(
                blank=True, default=None, max_length=1, null=True
            ),
        ),
        migrations.AlterField(
            model_name="ebipq_ecipq",
            name="cybv3",
            field=models.IntegerField(
                blank=True, default=None, max_length=1, null=True
            ),
        ),
        migrations.AlterField(
            model_name="ebipq_ecipq",
            name="vb1",
            field=models.IntegerField(
                blank=True, default=None, max_length=1, null=True
            ),
        ),
        migrations.AlterField(
            model_name="ebipq_ecipq",
            name="vb2",
            field=models.IntegerField(
                blank=True, default=None, max_length=1, null=True
            ),
        ),
        migrations.AlterField(
            model_name="ebipq_ecipq",
            name="vb4",
            field=models.IntegerField(
                blank=True, default=None, max_length=1, null=True
            ),
        ),
        migrations.AlterField(
            model_name="ed",
            name="ed1",
            field=models.IntegerField(
                blank=True, default=None, max_length=1, null=True
            ),
        ),
        migrations.AlterField(
            model_name="ed",
            name="ed10",
            field=models.IntegerField(
                blank=True, default=None, max_length=1, null=True
            ),
        ),
        migrations.AlterField(
            model_name="ed",
            name="ed11",
            field=models.IntegerField(
                blank=True, default=None, max_length=1, null=True
            ),
        ),
        migrations.AlterField(
            model_name="ed",
            name="ed12",
            field=models.IntegerField(
                blank=True, default=None, max_length=1, null=True
            ),
        ),
        migrations.AlterField(
            model_name="ed",
            name="ed13",
            field=models.IntegerField(
                blank=True, default=None, max_length=1, null=True
            ),
        ),
        migrations.AlterField(
            model_name="ed",
            name="ed14",
            field=models.IntegerField(
                blank=True, default=None, max_length=1, null=True
            ),
        ),
        migrations.AlterField(
            model_name="ed",
            name="ed15",
            field=models.IntegerField(
                blank=True, default=None, max_length=1, null=True
            ),
        ),
        migrations.AlterField(
            model_name="ed",
            name="ed16",
            field=models.IntegerField(
                blank=True, default=None, max_length=1, null=True
            ),
        ),
        migrations.AlterField(
            model_name="ed",
            name="ed2",
            field=models.IntegerField(
                blank=True, default=None, max_length=1, null=True
            ),
        ),
        migrations.AlterField(
            model_name="ed",
            name="ed3",
            field=models.IntegerField(
                blank=True, default=None, max_length=1, null=True
            ),
        ),
        migrations.AlterField(
            model_name="ed",
            name="ed4",
            field=models.IntegerField(
                blank=True, default=None, max_length=1, null=True
            ),
        ),
        migrations.AlterField(
            model_name="ed",
            name="ed5",
            field=models.IntegerField(
                blank=True, default=None, max_length=1, null=True
            ),
        ),
        migrations.AlterField(
            model_name="ed",
            name="ed6",
            field=models.IntegerField(
                blank=True, default=None, max_length=1, null=True
            ),
        ),
        migrations.AlterField(
            model_name="ed",
            name="ed7",
            field=models.IntegerField(
                blank=True, default=None, max_length=1, null=True
            ),
        ),
        migrations.AlterField(
            model_name="ed",
            name="ed8",
            field=models.IntegerField(
                blank=True, default=None, max_length=1, null=True
            ),
        ),
        migrations.AlterField(
            model_name="ed",
            name="ed9",
            field=models.IntegerField(
                blank=True, default=None, max_length=1, null=True
            ),
        ),
        migrations.AlterField(
            model_name="er",
            name="er1",
            field=models.IntegerField(
                blank=True, default=None, max_length=1, null=True
            ),
        ),
        migrations.AlterField(
            model_name="er",
            name="er10",
            field=models.IntegerField(
                blank=True, default=None, max_length=1, null=True
            ),
        ),
        migrations.AlterField(
            model_name="er",
            name="er2",
            field=models.IntegerField(
                blank=True, default=None, max_length=1, null=True
            ),
        ),
        migrations.AlterField(
            model_name="er",
            name="er3",
            field=models.IntegerField(
                blank=True, default=None, max_length=1, null=True
            ),
        ),
        migrations.AlterField(
            model_name="er",
            name="er4",
            field=models.IntegerField(
                blank=True, default=None, max_length=1, null=True
            ),
        ),
        migrations.AlterField(
            model_name="er",
            name="er5",
            field=models.IntegerField(
                blank=True, default=None, max_length=1, null=True
            ),
        ),
        migrations.AlterField(
            model_name="er",
            name="er6",
            field=models.IntegerField(
                blank=True, default=None, max_length=1, null=True
            ),
        ),
        migrations.AlterField(
            model_name="er",
            name="er7",
            field=models.IntegerField(
                blank=True, default=None, max_length=1, null=True
            ),
        ),
        migrations.AlterField(
            model_name="er",
            name="er8",
            field=models.IntegerField(
                blank=True, default=None, max_length=1, null=True
            ),
        ),
        migrations.AlterField(
            model_name="er",
            name="er9",
            field=models.IntegerField(
                blank=True, default=None, max_length=1, null=True
            ),
        ),
        migrations.AlterField(
            model_name="family",
            name="family1",
            field=models.CharField(blank=True, default=None, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name="family",
            name="family10",
            field=models.CharField(blank=True, default=None, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name="family",
            name="family11",
            field=models.CharField(blank=True, default=None, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name="family",
            name="family13",
            field=models.CharField(blank=True, default=None, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name="family",
            name="family2",
            field=models.CharField(blank=True, default=None, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name="family",
            name="family3",
            field=models.CharField(blank=True, default=None, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name="family",
            name="family4",
            field=models.CharField(blank=True, default=None, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name="family",
            name="family5",
            field=models.CharField(blank=True, default=None, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name="family",
            name="family6",
            field=models.CharField(blank=True, default=None, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name="family",
            name="family7",
            field=models.CharField(blank=True, default=None, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name="family",
            name="family8",
            field=models.CharField(blank=True, default=None, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name="family",
            name="family9",
            field=models.CharField(blank=True, default=None, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name="injury",
            name="inq1",
            field=models.IntegerField(
                blank=True, default=None, max_length=1, null=True
            ),
        ),
        migrations.AlterField(
            model_name="injury",
            name="inq10",
            field=models.IntegerField(
                blank=True, default=None, max_length=1, null=True
            ),
        ),
        migrations.AlterField(
            model_name="injury",
            name="inq11",
            field=models.IntegerField(
                blank=True, default=None, max_length=1, null=True
            ),
        ),
        migrations.AlterField(
            model_name="injury",
            name="inq12",
            field=models.IntegerField(
                blank=True, default=None, max_length=1, null=True
            ),
        ),
        migrations.AlterField(
            model_name="injury",
            name="inq13",
            field=models.IntegerField(
                blank=True, default=None, max_length=1, null=True
            ),
        ),
        migrations.AlterField(
            model_name="injury",
            name="inq14",
            field=models.IntegerField(
                blank=True, default=None, max_length=1, null=True
            ),
        ),
        migrations.AlterField(
            model_name="injury",
            name="inq15",
            field=models.IntegerField(
                blank=True, default=None, max_length=1, null=True
            ),
        ),
        migrations.AlterField(
            model_name="injury",
            name="inq2",
            field=models.IntegerField(
                blank=True, default=None, max_length=1, null=True
            ),
        ),
        migrations.AlterField(
            model_name="injury",
            name="inq3",
            field=models.IntegerField(
                blank=True, default=None, max_length=1, null=True
            ),
        ),
        migrations.AlterField(
            model_name="injury",
            name="inq4",
            field=models.IntegerField(
                blank=True, default=None, max_length=1, null=True
            ),
        ),
        migrations.AlterField(
            model_name="injury",
            name="inq5",
            field=models.IntegerField(
                blank=True, default=None, max_length=1, null=True
            ),
        ),
        migrations.AlterField(
            model_name="injury",
            name="inq6",
            field=models.IntegerField(
                blank=True, default=None, max_length=1, null=True
            ),
        ),
        migrations.AlterField(
            model_name="injury",
            name="inq7",
            field=models.IntegerField(
                blank=True, default=None, max_length=1, null=True
            ),
        ),
        migrations.AlterField(
            model_name="injury",
            name="inq8",
            field=models.IntegerField(
                blank=True, default=None, max_length=1, null=True
            ),
        ),
        migrations.AlterField(
            model_name="injury",
            name="inq9",
            field=models.IntegerField(
                blank=True, default=None, max_length=1, null=True
            ),
        ),
        migrations.AlterField(
            model_name="inq",
            name="inq1",
            field=models.IntegerField(
                blank=True, default=None, max_length=1, null=True
            ),
        ),
        migrations.AlterField(
            model_name="inq",
            name="inq10",
            field=models.IntegerField(
                blank=True, default=None, max_length=1, null=True
            ),
        ),
        migrations.AlterField(
            model_name="inq",
            name="inq11",
            field=models.IntegerField(
                blank=True, default=None, max_length=1, null=True
            ),
        ),
        migrations.AlterField(
            model_name="inq",
            name="inq12",
            field=models.IntegerField(
                blank=True, default=None, max_length=1, null=True
            ),
        ),
        migrations.AlterField(
            model_name="inq",
            name="inq13",
            field=models.IntegerField(
                blank=True, default=None, max_length=1, null=True
            ),
        ),
        migrations.AlterField(
            model_name="inq",
            name="inq14",
            field=models.IntegerField(
                blank=True, default=None, max_length=1, null=True
            ),
        ),
        migrations.AlterField(
            model_name="inq",
            name="inq15",
            field=models.IntegerField(
                blank=True, default=None, max_length=1, null=True
            ),
        ),
        migrations.AlterField(
            model_name="inq",
            name="inq2",
            field=models.IntegerField(
                blank=True, default=None, max_length=1, null=True
            ),
        ),
        migrations.AlterField(
            model_name="inq",
            name="inq3",
            field=models.IntegerField(
                blank=True, default=None, max_length=1, null=True
            ),
        ),
        migrations.AlterField(
            model_name="inq",
            name="inq4",
            field=models.IntegerField(
                blank=True, default=None, max_length=1, null=True
            ),
        ),
        migrations.AlterField(
            model_name="inq",
            name="inq5",
            field=models.IntegerField(
                blank=True, default=None, max_length=1, null=True
            ),
        ),
        migrations.AlterField(
            model_name="inq",
            name="inq6",
            field=models.IntegerField(
                blank=True, default=None, max_length=1, null=True
            ),
        ),
        migrations.AlterField(
            model_name="inq",
            name="inq7",
            field=models.IntegerField(
                blank=True, default=None, max_length=1, null=True
            ),
        ),
        migrations.AlterField(
            model_name="inq",
            name="inq8",
            field=models.IntegerField(
                blank=True, default=None, max_length=1, null=True
            ),
        ),
        migrations.AlterField(
            model_name="inq",
            name="inq9",
            field=models.IntegerField(
                blank=True, default=None, max_length=1, null=True
            ),
        ),
        migrations.AlterField(
            model_name="multicage_cad_4",
            name="mcad1",
            field=models.CharField(blank=True, default=None, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name="multicage_cad_4",
            name="mcad10",
            field=models.CharField(blank=True, default=None, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name="multicage_cad_4",
            name="mcad11",
            field=models.CharField(blank=True, default=None, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name="multicage_cad_4",
            name="mcad12",
            field=models.CharField(blank=True, default=None, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name="multicage_cad_4",
            name="mcad2",
            field=models.CharField(blank=True, default=None, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name="multicage_cad_4",
            name="mcad3",
            field=models.CharField(blank=True, default=None, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name="multicage_cad_4",
            name="mcad4",
            field=models.CharField(blank=True, default=None, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name="multicage_cad_4",
            name="mcad5",
            field=models.CharField(blank=True, default=None, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name="multicage_cad_4",
            name="mcad6",
            field=models.CharField(blank=True, default=None, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name="multicage_cad_4",
            name="mcad7",
            field=models.CharField(blank=True, default=None, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name="multicage_cad_4",
            name="mcad8",
            field=models.CharField(blank=True, default=None, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name="multicage_cad_4",
            name="mcad9",
            field=models.CharField(blank=True, default=None, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name="parq",
            name="parq1",
            field=models.IntegerField(
                blank=True, default=None, max_length=1, null=True
            ),
        ),
        migrations.AlterField(
            model_name="parq",
            name="parq10",
            field=models.IntegerField(
                blank=True, default=None, max_length=1, null=True
            ),
        ),
        migrations.AlterField(
            model_name="parq",
            name="parq11",
            field=models.IntegerField(
                blank=True, default=None, max_length=1, null=True
            ),
        ),
        migrations.AlterField(
            model_name="parq",
            name="parq12",
            field=models.IntegerField(
                blank=True, default=None, max_length=1, null=True
            ),
        ),
        migrations.AlterField(
            model_name="parq",
            name="parq13",
            field=models.IntegerField(
                blank=True, default=None, max_length=1, null=True
            ),
        ),
        migrations.AlterField(
            model_name="parq",
            name="parq14",
            field=models.IntegerField(
                blank=True, default=None, max_length=1, null=True
            ),
        ),
        migrations.AlterField(
            model_name="parq",
            name="parq15",
            field=models.IntegerField(
                blank=True, default=None, max_length=1, null=True
            ),
        ),
        migrations.AlterField(
            model_name="parq",
            name="parq16",
            field=models.IntegerField(
                blank=True, default=None, max_length=1, null=True
            ),
        ),
        migrations.AlterField(
            model_name="parq",
            name="parq17",
            field=models.IntegerField(
                blank=True, default=None, max_length=1, null=True
            ),
        ),
        migrations.AlterField(
            model_name="parq",
            name="parq18",
            field=models.IntegerField(
                blank=True, default=None, max_length=1, null=True
            ),
        ),
        migrations.AlterField(
            model_name="parq",
            name="parq19",
            field=models.IntegerField(
                blank=True, default=None, max_length=1, null=True
            ),
        ),
        migrations.AlterField(
            model_name="parq",
            name="parq2",
            field=models.IntegerField(
                blank=True, default=None, max_length=1, null=True
            ),
        ),
        migrations.AlterField(
            model_name="parq",
            name="parq20",
            field=models.IntegerField(
                blank=True, default=None, max_length=1, null=True
            ),
        ),
        migrations.AlterField(
            model_name="parq",
            name="parq21",
            field=models.IntegerField(
                blank=True, default=None, max_length=1, null=True
            ),
        ),
        migrations.AlterField(
            model_name="parq",
            name="parq22",
            field=models.IntegerField(
                blank=True, default=None, max_length=1, null=True
            ),
        ),
        migrations.AlterField(
            model_name="parq",
            name="parq23",
            field=models.IntegerField(
                blank=True, default=None, max_length=1, null=True
            ),
        ),
        migrations.AlterField(
            model_name="parq",
            name="parq24",
            field=models.IntegerField(
                blank=True, default=None, max_length=1, null=True
            ),
        ),
        migrations.AlterField(
            model_name="parq",
            name="parq25",
            field=models.IntegerField(
                blank=True, default=None, max_length=1, null=True
            ),
        ),
        migrations.AlterField(
            model_name="parq",
            name="parq26",
            field=models.IntegerField(
                blank=True, default=None, max_length=1, null=True
            ),
        ),
        migrations.AlterField(
            model_name="parq",
            name="parq27",
            field=models.IntegerField(
                blank=True, default=None, max_length=1, null=True
            ),
        ),
        migrations.AlterField(
            model_name="parq",
            name="parq28",
            field=models.IntegerField(
                blank=True, default=None, max_length=1, null=True
            ),
        ),
        migrations.AlterField(
            model_name="parq",
            name="parq29",
            field=models.IntegerField(
                blank=True, default=None, max_length=1, null=True
            ),
        ),
        migrations.AlterField(
            model_name="parq",
            name="parq3",
            field=models.IntegerField(
                blank=True, default=None, max_length=1, null=True
            ),
        ),
        migrations.AlterField(
            model_name="parq",
            name="parq4",
            field=models.IntegerField(
                blank=True, default=None, max_length=1, null=True
            ),
        ),
        migrations.AlterField(
            model_name="parq",
            name="parq5",
            field=models.IntegerField(
                blank=True, default=None, max_length=1, null=True
            ),
        ),
        migrations.AlterField(
            model_name="parq",
            name="parq6",
            field=models.IntegerField(
                blank=True, default=None, max_length=1, null=True
            ),
        ),
        migrations.AlterField(
            model_name="parq",
            name="parq7",
            field=models.IntegerField(
                blank=True, default=None, max_length=1, null=True
            ),
        ),
        migrations.AlterField(
            model_name="parq",
            name="parq8",
            field=models.IntegerField(
                blank=True, default=None, max_length=1, null=True
            ),
        ),
        migrations.AlterField(
            model_name="parq",
            name="parq9",
            field=models.IntegerField(
                blank=True, default=None, max_length=1, null=True
            ),
        ),
        migrations.AlterField(
            model_name="rrss",
            name="rrss1",
            field=models.CharField(blank=True, default=None, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name="rrss",
            name="rrss2",
            field=models.CharField(blank=True, default=None, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name="rrss",
            name="rrss3",
            field=models.CharField(blank=True, default=None, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name="rrss",
            name="rrss4",
            field=models.CharField(blank=True, default=None, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name="rrss",
            name="rrss5",
            field=models.CharField(blank=True, default=None, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name="rrss",
            name="rrss6",
            field=models.CharField(blank=True, default=None, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name="rrss",
            name="rrss7",
            field=models.CharField(blank=True, default=None, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name="sena",
            name="sena103",
            field=models.IntegerField(
                blank=True, default=None, max_length=1, null=True
            ),
        ),
        migrations.AlterField(
            model_name="sena",
            name="sena111",
            field=models.IntegerField(
                blank=True, default=None, max_length=1, null=True
            ),
        ),
        migrations.AlterField(
            model_name="sena",
            name="sena112",
            field=models.IntegerField(
                blank=True, default=None, max_length=1, null=True
            ),
        ),
        migrations.AlterField(
            model_name="sena",
            name="sena115",
            field=models.IntegerField(
                blank=True, default=None, max_length=1, null=True
            ),
        ),
        migrations.AlterField(
            model_name="sena",
            name="sena117",
            field=models.IntegerField(
                blank=True, default=None, max_length=1, null=True
            ),
        ),
        migrations.AlterField(
            model_name="sena",
            name="sena129",
            field=models.IntegerField(
                blank=True, default=None, max_length=1, null=True
            ),
        ),
        migrations.AlterField(
            model_name="sena",
            name="sena137",
            field=models.IntegerField(
                blank=True, default=None, max_length=1, null=True
            ),
        ),
        migrations.AlterField(
            model_name="sena",
            name="sena139",
            field=models.IntegerField(
                blank=True, default=None, max_length=1, null=True
            ),
        ),
        migrations.AlterField(
            model_name="sena",
            name="sena141",
            field=models.IntegerField(
                blank=True, default=None, max_length=1, null=True
            ),
        ),
        migrations.AlterField(
            model_name="sena",
            name="sena146",
            field=models.IntegerField(
                blank=True, default=None, max_length=1, null=True
            ),
        ),
        migrations.AlterField(
            model_name="sena",
            name="sena150",
            field=models.IntegerField(
                blank=True, default=None, max_length=1, null=True
            ),
        ),
        migrations.AlterField(
            model_name="sena",
            name="sena188",
            field=models.IntegerField(
                blank=True, default=None, max_length=1, null=True
            ),
        ),
        migrations.AlterField(
            model_name="sena",
            name="sena19",
            field=models.IntegerField(
                blank=True, default=None, max_length=1, null=True
            ),
        ),
        migrations.AlterField(
            model_name="sena",
            name="sena23",
            field=models.IntegerField(
                blank=True, default=None, max_length=1, null=True
            ),
        ),
        migrations.AlterField(
            model_name="sena",
            name="sena69",
            field=models.IntegerField(
                blank=True, default=None, max_length=1, null=True
            ),
        ),
        migrations.AlterField(
            model_name="sena",
            name="sena99",
            field=models.IntegerField(
                blank=True, default=None, max_length=1, null=True
            ),
        ),
        migrations.AlterField(
            model_name="social_data",
            name="age",
            field=models.IntegerField(
                blank=True, default=None, max_length=3, null=True
            ),
        ),
        migrations.AlterField(
            model_name="social_data",
            name="chronic_disease",
            field=models.CharField(blank=True, default=None, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name="social_data",
            name="female_others_perception",
            field=models.IntegerField(
                blank=True, default=None, max_length=1, null=True
            ),
        ),
        migrations.AlterField(
            model_name="social_data",
            name="female_self_perception",
            field=models.IntegerField(
                blank=True, default=None, max_length=1, null=True
            ),
        ),
        migrations.AlterField(
            model_name="social_data",
            name="male_others_perception",
            field=models.IntegerField(
                blank=True, default=None, max_length=1, null=True
            ),
        ),
        migrations.AlterField(
            model_name="social_data",
            name="male_self_perception",
            field=models.IntegerField(
                blank=True, default=None, max_length=1, null=True
            ),
        ),
        migrations.AlterField(
            model_name="social_data",
            name="previous_psychiatric_treatment",
            field=models.CharField(blank=True, default=None, max_length=2, null=True),
        ),
        migrations.CreateModel(
            name="SENA_FAMILY",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=20)),
                ("date", models.DateTimeField(blank=True, default=None, null=True)),
                (
                    "sena104",
                    models.IntegerField(
                        blank=True, default=None, max_length=1, null=True
                    ),
                ),
                (
                    "sena117",
                    models.IntegerField(
                        blank=True, default=None, max_length=1, null=True
                    ),
                ),
                (
                    "sena118",
                    models.IntegerField(
                        blank=True, default=None, max_length=1, null=True
                    ),
                ),
                (
                    "sena121",
                    models.IntegerField(
                        blank=True, default=None, max_length=1, null=True
                    ),
                ),
                (
                    "sena123",
                    models.IntegerField(
                        blank=True, default=None, max_length=1, null=True
                    ),
                ),
                (
                    "sena124",
                    models.IntegerField(
                        blank=True, default=None, max_length=1, null=True
                    ),
                ),
                (
                    "sena125",
                    models.IntegerField(
                        blank=True, default=None, max_length=1, null=True
                    ),
                ),
                (
                    "sena135",
                    models.IntegerField(
                        blank=True, default=None, max_length=1, null=True
                    ),
                ),
                (
                    "sena137",
                    models.IntegerField(
                        blank=True, default=None, max_length=1, null=True
                    ),
                ),
                (
                    "sena138",
                    models.IntegerField(
                        blank=True, default=None, max_length=1, null=True
                    ),
                ),
                (
                    "sena139",
                    models.IntegerField(
                        blank=True, default=None, max_length=1, null=True
                    ),
                ),
                (
                    "sena140",
                    models.IntegerField(
                        blank=True, default=None, max_length=1, null=True
                    ),
                ),
                (
                    "sena145",
                    models.IntegerField(
                        blank=True, default=None, max_length=1, null=True
                    ),
                ),
                (
                    "sena146",
                    models.IntegerField(
                        blank=True, default=None, max_length=1, null=True
                    ),
                ),
                (
                    "sena148",
                    models.IntegerField(
                        blank=True, default=None, max_length=1, null=True
                    ),
                ),
                (
                    "sena154",
                    models.IntegerField(
                        blank=True, default=None, max_length=1, null=True
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ATI",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=20)),
                ("date", models.DateTimeField(blank=True, default=None, null=True)),
                (
                    "ati1",
                    models.IntegerField(
                        blank=True, default=None, max_length=1, null=True
                    ),
                ),
                (
                    "ati2",
                    models.IntegerField(
                        blank=True, default=None, max_length=1, null=True
                    ),
                ),
                (
                    "ati3",
                    models.IntegerField(
                        blank=True, default=None, max_length=1, null=True
                    ),
                ),
                (
                    "ati4",
                    models.IntegerField(
                        blank=True, default=None, max_length=1, null=True
                    ),
                ),
                (
                    "ati5",
                    models.IntegerField(
                        blank=True, default=None, max_length=1, null=True
                    ),
                ),
                (
                    "ati6",
                    models.IntegerField(
                        blank=True, default=None, max_length=1, null=True
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ATE",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=20)),
                ("date", models.DateTimeField(blank=True, default=None, null=True)),
                (
                    "ate1",
                    models.IntegerField(
                        blank=True, default=None, max_length=1, null=True
                    ),
                ),
                (
                    "ate2",
                    models.IntegerField(
                        blank=True, default=None, max_length=1, null=True
                    ),
                ),
                (
                    "ate3",
                    models.IntegerField(
                        blank=True, default=None, max_length=1, null=True
                    ),
                ),
                (
                    "ate4",
                    models.IntegerField(
                        blank=True, default=None, max_length=1, null=True
                    ),
                ),
                (
                    "ate5",
                    models.IntegerField(
                        blank=True, default=None, max_length=1, null=True
                    ),
                ),
                (
                    "ate6",
                    models.IntegerField(
                        blank=True, default=None, max_length=1, null=True
                    ),
                ),
                (
                    "ate7",
                    models.IntegerField(
                        blank=True, default=None, max_length=1, null=True
                    ),
                ),
                (
                    "ate8",
                    models.IntegerField(
                        blank=True, default=None, max_length=1, null=True
                    ),
                ),
                (
                    "ate9",
                    models.IntegerField(
                        blank=True, default=None, max_length=1, null=True
                    ),
                ),
                (
                    "ate10",
                    models.IntegerField(
                        blank=True, default=None, max_length=1, null=True
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
