# Generated by Django 4.2.13 on 2024-07-23 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sivaria", "0020_alter_ate_ate1_alter_ate_ate10_alter_ate_ate2_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="social_data",
            name="female_others_perception",
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name="social_data",
            name="male_others_perception",
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
