# Generated by Django 4.2.13 on 2024-07-23 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sivaria", "0022_remove_ate_code_remove_ate_date_remove_ate_user_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="professionalforms",
            old_name="to_user",
            new_name="to_user_professional_form",
        ),
        migrations.AddField(
            model_name="familyforms",
            name="code",
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="professionalforms",
            name="code",
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="youngforms",
            name="code",
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="familyforms",
            name="date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="professionalforms",
            name="date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="youngforms",
            name="date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
