# Generated by Django 4.2.13 on 2024-07-24 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "sivaria",
            "0023_rename_to_user_professionalforms_to_user_professional_form_and_more",
        ),
    ]

    operations = [
        migrations.RenameModel(
            old_name="FamilyForms",
            new_name="FamilyForm",
        ),
        migrations.RenameModel(
            old_name="ProfessionalForms",
            new_name="ProfessionalForm",
        ),
        migrations.RenameModel(
            old_name="YoungForms",
            new_name="YoungForm",
        ),
    ]
