# Generated by Django 4.2.13 on 2024-07-24 09:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("sivaria", "0025_rename_er_ateform_rename_ati_atiform_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="youngform",
            name="ate",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="sivaria.ateform",
            ),
        ),
        migrations.AlterField(
            model_name="youngform",
            name="er",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="sivaria.erform",
            ),
        ),
    ]
