# Generated by Django 4.2.13 on 2024-07-24 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sivaria", "0026_alter_youngform_ate_alter_youngform_er"),
    ]

    operations = [
        migrations.AddField(
            model_name="ateform",
            name="code",
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="atiform",
            name="code",
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="cerqsform",
            name="code",
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="ebipqecipqform",
            name="code",
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="edform",
            name="code",
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="erform",
            name="code",
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="familysubform",
            name="code",
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="injuryform",
            name="code",
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="inqform",
            name="code",
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="multicagecad4form",
            name="code",
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="parqform",
            name="code",
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="rrssform",
            name="code",
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="senafamilyform",
            name="code",
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="senaform",
            name="code",
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="socialdataform",
            name="code",
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
    ]
