# Generated by Django 4.2.13 on 2024-07-24 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sivaria", "0028_alter_appuser_code_alter_ateform_code_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="familysubform",
            old_name="family1",
            new_name="adiccion_padre_madre",
        ),
        migrations.RenameField(
            model_name="familysubform",
            old_name="family10",
            new_name="duelo",
        ),
        migrations.RenameField(
            model_name="familysubform",
            old_name="family11",
            new_name="familia_monoparental",
        ),
        migrations.RenameField(
            model_name="familysubform",
            old_name="family13",
            new_name="familia_reconstruida",
        ),
        migrations.RenameField(
            model_name="familysubform",
            old_name="family12",
            new_name="ingreso_familiar_mensual",
        ),
        migrations.RenameField(
            model_name="familysubform",
            old_name="family2",
            new_name="madre_adolescente",
        ),
        migrations.RenameField(
            model_name="familysubform",
            old_name="family3",
            new_name="maltrato_a_la_pareja",
        ),
        migrations.RenameField(
            model_name="familysubform",
            old_name="family4",
            new_name="maltrato_al_adolescente",
        ),
        migrations.RenameField(
            model_name="familysubform",
            old_name="family5",
            new_name="padre_adolescente",
        ),
        migrations.RenameField(
            model_name="familysubform",
            old_name="family6",
            new_name="padres_divorciados",
        ),
        migrations.RenameField(
            model_name="familysubform",
            old_name="family7",
            new_name="relaciones_conflictivas_hijo_padre_madre",
        ),
        migrations.RenameField(
            model_name="familysubform",
            old_name="family8",
            new_name="situacion_economica_precaria",
        ),
        migrations.RenameField(
            model_name="familysubform",
            old_name="family9",
            new_name="supervision_parental_insuficiente",
        ),
        migrations.AddField(
            model_name="familysubform",
            name="tratamiento_psicologico_padre_madre",
            field=models.CharField(blank=True, default=None, max_length=2, null=True),
        ),
    ]
