# Generated by Django 4.2.13 on 2024-07-24 19:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("sivaria", "0029_rename_family1_familysubform_adiccion_padre_madre_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="professionalform",
            name="social_data",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="sivaria.socialdataform",
            ),
        ),
    ]
