# Generated by Django 4.2.13 on 2024-07-25 16:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("sivaria", "0030_professionalform_social_data"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="appuser",
            name="assigned_to",
        ),
        migrations.AddField(
            model_name="userhasparent",
            name="responsible",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="responsible",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
