# Generated by Django 4.2.13 on 2024-07-26 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sivaria", "0031_remove_appuser_assigned_to_userhasparent_responsible"),
    ]

    operations = [
        migrations.RenameField(
            model_name="userhasparent",
            old_name="son",
            new_name="child",
        ),
    ]
