# Generated by Django 4.2.14 on 2024-07-29 19:52

from django.db import migrations

def add_initial_roles(apps, schema_editor):
    Rol = apps.get_model('your_app_name', 'Rol')
    Rol.objects.create(slug='joven', description='Joven', code='J')
    Rol.objects.create(slug='padre', description='Padre', code='P')
    Rol.objects.create(slug='madre', description='Madre', code='M')
    Rol.objects.create(slug='profesional', description='Profesional', code='Pr')

class Migration(migrations.Migration):

    dependencies = [
        ('your_app_name', 'previous_migration_name'),
    ]

    operations = [
        migrations.RunPython(add_initial_roles),
    ]
