# Generated by Django 4.2.14 on 2024-07-29 19:52

from django.db import migrations

def add_initial_roles(apps, schema_editor):
    Rol = apps.get_model('sivaria', 'Rol')

    roles = [
        {"slug": "joven", "description": "Joven", "code": "J"},
        {"slug": "padre", "description": "Padre", "code": "P"},
        {"slug": "madre", "description": "Madre", "code": "M"},
        {"slug": "profesional", "description": "Profesional", "code": "Pr"},
    ]

    for role in roles:
        if not Rol.objects.filter(slug=role['slug']).exists():
            Rol.objects.create(**role)

class Migration(migrations.Migration):

    dependencies = [
        ('sivaria', '0032_rename_son_userhasparent_child'),
    ]

    operations = [
        migrations.RunPython(add_initial_roles),
    ]
