# Generated by Django 4.2.14 on 2024-08-04 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sivaria', '0033_add_initial_roles'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
