# Generated by Django 4.2.14 on 2024-08-16 15:54

from django.db import migrations

def add_initial_push_templates(apps, schema_editor):
    MyModel = apps.get_model('sivaria', 'PushNotificationType')
    MyModel.objects.create(slug="riesgo_moderado_padres", title="Notificación de nivel de riesgo MODERADO para padres", body="El usuario ha sido analizado y hay un riesgo moderado en adoptar conductas autolesivas no suicidas o suicidas.", data="")
    MyModel.objects.create(slug="riesgo_ausente_padres", title="Notificación de nivel de riesgo AUSENTE para padres", body="El usuario ha sido analizado y no se han encontrado riesgos de que pueda adoptar conductas autolesivas suicidas o no suicidas.", data="")
    MyModel.objects.create(slug="riesgo_leve_padres", title="Notificación de nivel de riesgo LEVE para padres", body="El usuario ha sido analizado y hay un riesgo leve en adoptar conductas autolesivas no suicidas o suicidas.", data="")
    MyModel.objects.create(slug="riesgo_grave_padres", title="Notificación de nivel de riesgo GRAVE para padres", body="El usuario ha sido analizado y hay un riesgo grave en adoptar conductas autolesivas suicidas.", data="")
    MyModel.objects.create(slug="emergencia_padres", title="Notificación de nivel de EMERGENCIA para padres", body="El usuario ha sido analizado y hay un riesgo elevado en adoptar conductas autolesivas suicidas.", data="")
    MyModel.objects.create(slug="emergencia_profesional", title="EMERGENCIA - Nivel de alerta 4 - Profesionales", body="El usuario ha sido analizado y ha recibido la calificación de EMERGENCIA en el riesgo de adoptar conductas autolesivas suicidas. Se deben aplicar medidas inmediatas al usuario. El resultado de la predicción es el siguiente: {{desenlace}}.", data="")
    MyModel.objects.create(slug="riesgo_grave_profesional", title="Riesgo GRAVE - Nivel de alerta 3 - Profesionales", body="El usuario ha sido analizado y hay un riesgo grave en adoptar conductas autolesivas no suicidas o suicidas. El resultado de la predicción es el siguiente: {{desenlace}}.", data="")
    MyModel.objects.create(slug="riesgo_moderado_profesional", title="Riesgo MODERADO - Nivel de alerta 2 - Profesionales", body="El usuario ha sido analizado y hay un riesgo moderado en adoptar conductas autolesivas no suicidas o suicidas. El resultado de la predicción ha sido el siguiente: {{desenlace}}.", data="")
    MyModel.objects.create(slug="riesgo_leve_profesional", title="Riesgo LEVE - Nivel de alerta 1 - Profesionales", body="El usuario ha sido analizado y hay un riesgo leve en adoptar conductas autolesivas no suicidas o suicidas. El resultado de la predicción es el siguiente: {{desenlace}}.", data="")
    MyModel.objects.create(slug="riesgo_ausente_profesional", title="Riiesgo AUSENTE -  Nivel de alerta 0 - Profesionales", body="El usuario ha sido analizado y hay un riesgo ausente en adoptar conductas autolesivas no suicidas o suicidas. El resultado de la predicción es el siguiente: {{desenlace}}.", data="")
    MyModel.objects.create(slug="example", title="Título de ejemplo de SIVARIA", body="Texto de ejemplo de SIVARIA", data="")

class Migration(migrations.Migration):

    dependencies = [
        ('sivaria', '0035_seed_email_templates'),
    ]

    operations = [
        migrations.RunPython(add_initial_push_templates),
    ]

