FIELDS = [
    'Index',
    'Nombre',
    'Edad',
    'Curso',
    'Peso',
    'Altura',
    'Sexo asignado',
    'Transgenero',
    'Nivel promedio del rendimiento academico',
    'Situacion laboral madre',
    'Situacion laboral padre',
    'Nivel profesional madre',
    'Nivel profesional padre',
    'Nivel de autopercepcion masculina',
    'Nivel de autopercepcion femenina',
    'Nivel de heteropercepcion masculina',
    'Nivel de heteropercepcion femenina',
    'Tratamiento psiquiatrico previo',
    'Presenta enfermedad cronica',
    'Bullying victima',
    'Bullying perpetrador',
    'Cyberbullying victima',
    'Cyberbullying perpetrador',
    'Adiccion/abuso alcohol',
    'Adiccion/abuso sustancias',
    'Adiccion/abuso Internet',
    'Problemas interiorizados',
    'Problemas exteriorizados',
    'Problemas de contexto',
    'Problemas recursos psicologicos',
    'Percepcion de discriminacion',
    'Fuente de discriminacion',
    'Nivel de resistencia/resiliencia',
    'Nivel de regulacion positiva',
    'Nivel de regulacion negativa',
    'Atrapamiento interno',
    'Atrapamiento externo',
    'Nivel percibido de derrota o fracaso',
    'Sentido de pertenencia frustada',
    'Percepcion de ser una carga',
    'Autoeficiencia para el suicidio',
    'Madre adolescente',
    'Padre adolescente',
    'Padres divorciados',
    'Familia monoparental',
    'Tratamiento psicologico padre/madre',
    'Adiccion padre/madre',
    'Relaciones conflictivas hijo-padre/madre',
    'Familia reconstruida',
    'Busqueda informacion autolesion',
    'Compartir en RRSS pensamiento autolesion',
    'Peticion ayuda en Internet',
    'Contagio',
    'Tener conocidos que comparten autolesion en Internet',
    'Via de contacto para RRSS',
    'Contacto informacion autolesion',
    'Denuncia autolesion Internet',
    'Desenlace'
]

FAMILY_FIELDS = [
    'Index',
    'Nombre',
    'Edad',
    'Curso',
    'Peso',
    'Altura',
    'Sexo asignado',
    'Transgenero',
    'Problemas interiorizados',
    'Problemas exteriorizados',
    'Problemas de contexto',
    'Problemas recursos psicologicos',
    'Madre adolescente',
    'Padre adolescente',
    'Padres divorciados',
    'Familia monoparental',
    'Tratamiento psicologico padre/madre',
    'Adiccion padre/madre',
    'Relaciones conflictivas hijo-padre/madre',
    'Familia reconstruida',
    'Aceptacion/rechazo parental',
    'Control parental',
    'Desenlace'
]

PROFESSIONAL_FIELDS = [
    'Index',
    'Nombre',
    'Edad',
    'Curso',
    'Peso',
    'Altura',
    'Sexo asignado',
    'Transgenero',
    'Madre adolescente',
    'Padre adolescente',
    'Padres divorciados',
    'Familia monoparental',
    'Tratamiento psicologico padre/madre',
    'Adiccion padre/madre',
    'Relaciones conflictivas hijo-padre/madre',
    'Familia reconstruida',
    'Situacion economica familiar precaria',
    'Estudios de la madre',
    'Estudios del padre',
    'Supervision parental insuficiente',
    'Maltrato al adolescente',
    'Duelo',
    'Ingreso familiar mensual',
    'Desenlace'
]

NAMES = [
    'Tom',
    'Marco',
    'Marcos',
    'Jenny',
    'Paul',
    'Penny',
    'Cristian',
    'Ronald',
    'Steve',
    'Jude',
    'Teddy',
    'Ted',
    'Wes',
    'Phil',
    'Harry',
    'Adebayo',
    'Rome',
    'Richard',
    'Robert',
    'Sean',
    'John',
    'Johnny',
    'Marcus',
    'Steven',
    'Frank',
    'Kyle',
    'Jordan',
    'Michael',
    'Landon',
    'Ronnie',
    'Cindy',
    'Lara',
    'Lucy',
    'Charlie',
    'Charles',
    'Andrew',
    'Mary',
    'Veronica',
    'Zara',
    'Kenny',
    'Tiffany',
    'Ernest',
    'Amelia',
    'Rachel',
    'Fred',
    'Frederick',
    'Osborn',
    'Peter',
    'Jeff',
    'Jeffrey',
    'Inma',
    'Yui',
    'Tadeo',
    'Ollie',
    'Morgan',
    'Luke',
    'Nathan',
    'Maxwell',
    'Max',
    'Jack',
    'Gero',
    'Geronimo',
    'Nemo',
    'Martin',
    'Marlon',
    'Mariana',
    'Daiana',
    'Daisy',
    'Luigi',
    'Ada',
    'Lisa',
    'Luisa',
    'Marge',
    'Bernie',
    'Bernard',
    'Dominic',
    'Declan',
    'David',
    'Davidson',
    'Dean',
    'Danny',
    'Daniel',
    'Domi',
    'Duke',
    'Fikayo',
    'Fernando',
    'Fernand',
    'Ferdinand',
    'Rio',
    'Theo',
    'Luka',
    'Lucas',
    'Luca',
    'Lana',
    'Larry',
    'Mike',
    'Bertin',
    'Lewis',
    'Lance',
    'Tim',
    'Timothy',
    'Eoin'
]
SURNAMES = [
    'Smith',
    'Johnson',
    'Williams',
    'Brown',
    'Jones',
    'Miller',
    'Davis',
    'Garcia',
    'Rodriguez',
    'Gonzalez',
    'Wilson',
    'Martinez',
    'Anderson',
    'Taylor',
    'Thomas',
    'Hernandez',
    'Moore',
    'Martin',
    'Jackson',
    'Perez',
    'Lewis',
    'Harris',
    'Clark',
    'Lee',
    'Walker',
    'Hall',
    'Allen',
    'Young',
    'King',
    'Wright',
    'Lopez',
    'Hill',
    'Scott',
    'Green',
    'Adams',
    'Baker',
    'Gomez',
    'Nelson',
    'Carter',
    'Evans',
    'Murphy',
    'Ramos',
    'Parker',
    'Cook',
    'James',
    'Morales',
    'Collins',
    'Bell',
    'Sanchez',
    'Fisher',
    'Cooper',
    'Gutierrez',
    'Brooks',
    'Kelly',
    'Sanders',
    'Price',
    'Bennett',
    'Wood',
    'Barnes',
    'Gray',
    'Fernandez',
    'James',
    'Watson',
    'Diaz',
    'Ramsey',
    'Stewart',
    'Foster',
    'Russell',
    'Jordan',
    'Bryant',
    'Alexander',
    'Russell',
    'Shaw',
    'Olson',
]

GENDERS = [
    'Mujer',
    'Hombre',
    'Otro'
]

TRASGENDER = [
    'Si',
    'No',
    'No estoy seguro de ser trans',
    'No estoy seguro de lo que se pregunta'
]

ACADEMIC_PERFORMANCES = [
    'Insuficiente',
    'Suficiente',
    'Notable',
    'Sobresaliente',
    'Extraordinario'
]

JOB_SITUATIONS = [
    'Trabaja',
    'No trabaja',
    'Pensionado'
]

LEVELS = [
    'Bajo',
    'Medio',
    'Alto'
]

COURSES = [
    'Colegio',
    'ESO',
    'Bachillerato',
    'Universidad',
    'Formacion Profesional'
]

YES_NO_ANSWERS = [
    'Si',
    'No'
]

DISCRIMINATION_SOURCE = [
    'Edad',
    'Raza',
    'Discapacidad',
    'Genero',
    'Orientacion sexual'
]

PARENT_BEHAVIOR = [
    'Aceptacion',
    'Rechazo'
]

FINAL_RESULT = [
    'Comunicacion',
    'Deseo',
    'Ideacion',
    'Planificacion',
    'Intencion',
    'Finalidad'
]