DATASET_BASEPATH = 'csvCreator/datasets'
MODEL_FILENAME = 'ModelExpertSystem.bif'

AUTOINFORME_MODEL_FILENAME = 'AutoinformeModelExpertSystem.bif'
FAMILY_MODEL_FILENAME = 'FamilyModelExpertSystem.bif'
PROFESSIONAL_MODEL_FILENAME = 'ProfessionalModelExpertSystem.bif'

MODEL_FILETYPE = '.bif'
MODEL_PRIOR_TYPE = 'BDeu'
CORRELATION_SCORE_SIGNIFICANCE_LEVEL = 0.05
CORRELATION_SCORE_STATISTICAL_TEST = 'chi_square'

TRAINING_PERCENTAGE_DATASET = 0.75

BAYES_NETWORK_VARIABLES = [
    'Curso', 
    'Sexo asignado', 
    'Transgenero', 
    'Edad', 
    'Situacion laboral padre', 
    'Situacion laboral madre', 
    'Nivel profesional padre', 
    'Nivel profesional madre',
    'Nivel promedio del rendimiento academico',
    'Nivel de autopercepcion masculina',
    'Nivel de autopercepcion femenina',
    'Nivel de heteropercepcion masculina',
    'Nivel de heteropercepcion femenina',
    'Altura',
    'Peso',
    'Tratamiento psiquiatrico previo',
    'Presenta enfermedad cronica',
    'Bullying victima',
    'Bullying perpetrador',
    'Cyberbullying victima',
    'Cyberbullying perpetrador',
    'Adiccion/abuso alcohol',
    'Adiccion/abuso sustancias',
    'Adiccion/abuso Internet',
    'Problemas interiorizados',
    'Problemas exteriorizados',
    'Problemas de contexto',
    'Problemas recursos psicologicos',
    'Percepcion de discriminacion',
    'Fuente de discriminacion',
    'Nivel de resistencia/resiliencia',
    'Nivel de regulacion positiva',
    'Nivel de regulacion negativa',
    'Atrapamiento interno',
    'Atrapamiento externo',
    'Nivel percibido de derrota o fracaso',
    'Sentido de pertenencia frustada',
    'Percepcion de ser una carga',
    'Autoeficiencia para el suicidio',
    'Madre adolescente',
    'Padre adolescente',
    'Padres divorciados',
    'Familia monoparental',
    'Tratamiento psicologico padre/madre',
    'Adiccion padre/madre',
    'Relaciones conflictivas hijo-padre/madre',
    'Familia reconstruida',
    'Busqueda informacion autolesion',
    'Compartir en RRSS pensamiento autolesion',
    'Peticion ayuda en Internet',
    'Contagio', 
    'Tener conocidos que comparten autolesion en Internet',
    'Via de contacto para RRSS',
    'Contacto informacion autolesion',
    'Denuncia autolesion Internet',
    'Aceptacion/rechazo parental',
    'Control parental',
    'Situacion economica familiar precaria',
    'Estudios de la madre',
    'Estudios del padre',
    'Supervision parental insuficiente',
    'Maltrato al adolescente',
    'Duelo',
    'Ingreso familiar mensual',
    'Desenlace'
]

BAYES_NETWORK_VARIABLES_AUTOINFORME = [
    'Curso', 
    'Sexo asignado', 
    'Transgenero', 
    'Edad', 
    'Situacion laboral padre', 
    'Situacion laboral madre', 
    'Nivel profesional padre', 
    'Nivel profesional madre',
    'Nivel promedio del rendimiento academico',
    'Nivel de autopercepcion masculina',
    'Nivel de autopercepcion femenina',
    'Nivel de heteropercepcion masculina',
    'Nivel de heteropercepcion femenina',
    'Altura',
    'Peso',
    'Tratamiento psiquiatrico previo',
    'Presenta enfermedad cronica',
    'Bullying victima',
    'Bullying perpetrador',
    'Cyberbullying victima',
    'Cyberbullying perpetrador',
    'Adiccion/abuso alcohol',
    'Adiccion/abuso sustancias',
    'Adiccion/abuso Internet',
    'Problemas interiorizados',
    'Problemas exteriorizados',
    'Problemas de contexto',
    'Problemas recursos psicologicos',
    'Percepcion de discriminacion',
    'Fuente de discriminacion',
    'Nivel de resistencia/resiliencia',
    'Nivel de regulacion positiva',
    'Nivel de regulacion negativa',
    'Atrapamiento interno',
    'Atrapamiento externo',
    'Nivel percibido de derrota o fracaso',
    'Sentido de pertenencia frustada',
    'Percepcion de ser una carga',
    'Autoeficiencia para el suicidio',
    'Madre adolescente',
    'Padre adolescente',
    'Padres divorciados',
    'Familia monoparental',
    'Tratamiento psicologico padre/madre',
    'Adiccion padre/madre',
    'Relaciones conflictivas hijo-padre/madre',
    'Familia reconstruida',
    'Busqueda informacion autolesion',
    'Compartir en RRSS pensamiento autolesion',
    'Peticion ayuda en Internet',
    'Contagio', 
    'Tener conocidos que comparten autolesion en Internet',
    'Via de contacto para RRSS',
    'Contacto informacion autolesion',
    'Denuncia autolesion Internet',
    'Desenlace'
]

BAYES_NETWORK_VARIABLES_FAMILY = [
    'Curso', 
    'Sexo asignado', 
    'Transgenero', 
    'Edad',
    'Altura',
    'Peso',
    'Problemas interiorizados',
    'Problemas exteriorizados',
    'Problemas de contexto',
    'Problemas recursos psicologicos',
    'Madre adolescente',
    'Padre adolescente',
    'Padres divorciados',
    'Familia monoparental',
    'Tratamiento psicologico padre/madre',
    'Adiccion padre/madre',
    'Relaciones conflictivas hijo-padre/madre',
    'Familia reconstruida',
    'Aceptacion/rechazo parental',
    'Control parental',
    'Desenlace'
]

BAYES_NETWORK_VARIABLES_PROFESSIONAL = [
    'Curso', 
    'Sexo asignado', 
    'Transgenero', 
    'Edad', 
    'Altura',
    'Peso',
    'Madre adolescente',
    'Padre adolescente',
    'Padres divorciados',
    'Familia monoparental',
    'Tratamiento psicologico padre/madre',
    'Adiccion padre/madre',
    'Relaciones conflictivas hijo-padre/madre',
    'Familia reconstruida',
    'Situacion economica familiar precaria',
    'Estudios de la madre',
    'Estudios del padre',
    'Supervision parental insuficiente',
    'Maltrato al adolescente',
    'Duelo',
    'Ingreso familiar mensual',
    'Desenlace'
]

BAYES_NETWORK_EDGES = [
    ('Curso', 'Desenlace'),
    ('Sexo asignado', 'Desenlace'),
    ('Transgenero', 'Desenlace'),
    ('Edad', 'Desenlace'),
    ('Situacion laboral padre', 'Desenlace'),
    ('Situacion laboral madre', 'Desenlace'),
    ('Nivel profesional padre', 'Desenlace'),
    ('Nivel profesional madre', 'Desenlace'),
    ('Nivel promedio del rendimiento academico', 'Desenlace'),
    ('Nivel de autopercepcion masculina', 'Desenlace'),
    ('Nivel de autopercepcion femenina', 'Desenlace'),
    ('Nivel de heteropercepcion masculina', 'Desenlace'),
    ('Nivel de heteropercepcion femenina', 'Desenlace'),
    ('Altura', 'Desenlace'),
    ('Peso', 'Desenlace'),
    ('Tratamiento psiquiatrico previo', 'Desenlace'),
    ('Presenta enfermedad cronica', 'Desenlace'),
    ('Bullying victima', 'Desenlace'),
    ('Bullying perpetrador', 'Desenlace'),
    ('Cyberbullying victima', 'Desenlace'),
    ('Cyberbullying perpetrador', 'Desenlace'),
    ('Adiccion/abuso alcohol', 'Desenlace'),
    ('Adiccion/abuso sustancias', 'Desenlace'),
    ('Adiccion/abuso Internet', 'Desenlace'),
    ('Problemas interiorizados', 'Desenlace'),
    ('Problemas exteriorizados', 'Desenlace'),
    ('Problemas de contexto', 'Desenlace'),
    ('Problemas recursos psicologicos', 'Desenlace'),
    ('Percepcion de discriminacion', 'Desenlace'),
    ('Fuente de discriminacion', 'Desenlace'),
    ('Nivel de resistencia/resiliencia', 'Desenlace'),
    ('Nivel de regulacion positiva', 'Desenlace'),
    ('Nivel de regulacion negativa', 'Desenlace'),
    ('Atrapamiento interno', 'Desenlace'),
    ('Atrapamiento externo', 'Desenlace'),
    ('Nivel percibido de derrota o fracaso', 'Desenlace'),
    ('Sentido de pertenencia frustada', 'Desenlace'),
    ('Percepcion de ser una carga', 'Desenlace'),
    ('Autoeficiencia para el suicidio', 'Desenlace'),
    ('Madre adolescente', 'Desenlace'),
    ('Padre adolescente', 'Desenlace'),
    ('Padres divorciados', 'Desenlace'),
    ('Familia monoparental', 'Desenlace'),
    ('Tratamiento psicologico padre/madre', 'Desenlace'),
    ('Adiccion padre/madre', 'Desenlace'),
    ('Relaciones conflictivas hijo-padre/madre', 'Desenlace'),
    ('Familia reconstruida', 'Desenlace'),
    ('Busqueda informacion autolesion', 'Desenlace'),
    ('Compartir en RRSS pensamiento autolesion', 'Desenlace'),
    ('Peticion ayuda en Internet', 'Desenlace'),
    ('Contagio', 'Desenlace'),
    ('Tener conocidos que comparten autolesion en Internet', 'Desenlace'),
    ('Via de contacto para RRSS', 'Desenlace'),
    ('Contacto informacion autolesion', 'Desenlace'),
    ('Denuncia autolesion Internet', 'Desenlace'),
    ('Aceptacion/rechazo parental', 'Desenlace'),
    ('Control parental', 'Desenlace'),
    ('Situacion economica familiar precaria', 'Desenlace'),
    ('Estudios de la madre', 'Desenlace'),
    ('Estudios del padre', 'Desenlace'),
    ('Supervision parental insuficiente', 'Desenlace'),
    ('Maltrato al adolescente', 'Desenlace'),
    ('Duelo', 'Desenlace'),
    ('Ingreso familiar mensual', 'Desenlace')
]

BAYES_NETWORK_EDGES_AUTOINFORME = [
    ('Curso', 'Desenlace'),
    ('Sexo asignado', 'Desenlace'),
    ('Transgenero', 'Desenlace'),
    ('Edad', 'Desenlace'),
    ('Situacion laboral padre', 'Desenlace'),
    ('Situacion laboral madre', 'Desenlace'),
    ('Nivel profesional padre', 'Desenlace'),
    ('Nivel profesional madre', 'Desenlace'),
    ('Nivel promedio del rendimiento academico', 'Desenlace'),
    ('Nivel de autopercepcion masculina', 'Desenlace'),
    ('Nivel de autopercepcion femenina', 'Desenlace'),
    ('Nivel de heteropercepcion masculina', 'Desenlace'),
    ('Nivel de heteropercepcion femenina', 'Desenlace'),
    ('Altura', 'Desenlace'),
    ('Peso', 'Desenlace'),
    ('Tratamiento psiquiatrico previo', 'Desenlace'),
    ('Presenta enfermedad cronica', 'Desenlace'),
    ('Bullying victima', 'Desenlace'),
    ('Bullying perpetrador', 'Desenlace'),
    ('Cyberbullying victima', 'Desenlace'),
    ('Cyberbullying perpetrador', 'Desenlace'),
    ('Adiccion/abuso alcohol', 'Desenlace'),
    ('Adiccion/abuso sustancias', 'Desenlace'),
    ('Adiccion/abuso Internet', 'Desenlace'),
    ('Problemas interiorizados', 'Desenlace'),
    ('Problemas exteriorizados', 'Desenlace'),
    ('Problemas de contexto', 'Desenlace'),
    ('Problemas recursos psicologicos', 'Desenlace'),
    ('Percepcion de discriminacion', 'Desenlace'),
    ('Fuente de discriminacion', 'Desenlace'),
    ('Nivel de resistencia/resiliencia', 'Desenlace'),
    ('Nivel de regulacion positiva', 'Desenlace'),
    ('Nivel de regulacion negativa', 'Desenlace'),
    ('Atrapamiento interno', 'Desenlace'),
    ('Atrapamiento externo', 'Desenlace'),
    ('Nivel percibido de derrota o fracaso', 'Desenlace'),
    ('Sentido de pertenencia frustada', 'Desenlace'),
    ('Percepcion de ser una carga', 'Desenlace'),
    ('Autoeficiencia para el suicidio', 'Desenlace'),
    ('Madre adolescente', 'Desenlace'),
    ('Padre adolescente', 'Desenlace'),
    ('Padres divorciados', 'Desenlace'),
    ('Familia monoparental', 'Desenlace'),
    ('Tratamiento psicologico padre/madre', 'Desenlace'),
    ('Adiccion padre/madre', 'Desenlace'),
    ('Relaciones conflictivas hijo-padre/madre', 'Desenlace'),
    ('Familia reconstruida', 'Desenlace'),
    ('Busqueda informacion autolesion', 'Desenlace'),
    ('Compartir en RRSS pensamiento autolesion', 'Desenlace'),
    ('Peticion ayuda en Internet', 'Desenlace'),
    ('Contagio', 'Desenlace'),
    ('Tener conocidos que comparten autolesion en Internet', 'Desenlace'),
    ('Via de contacto para RRSS', 'Desenlace'),
    ('Contacto informacion autolesion', 'Desenlace'),
    ('Denuncia autolesion Internet', 'Desenlace'),
]

BAYES_NETWORK_EDGES_FAMILY = [
    ('Curso', 'Desenlace'),
    ('Sexo asignado', 'Desenlace'),
    ('Transgenero', 'Desenlace'),
    ('Edad', 'Desenlace'),
    ('Peso', 'Desenlace'),
    ('Problemas interiorizados', 'Desenlace'),
    ('Problemas exteriorizados', 'Desenlace'),
    ('Problemas de contexto', 'Desenlace'),
    ('Problemas recursos psicologicos', 'Desenlace'),
    ('Madre adolescente', 'Desenlace'),
    ('Padre adolescente', 'Desenlace'),
    ('Padres divorciados', 'Desenlace'),
    ('Familia monoparental', 'Desenlace'),
    ('Tratamiento psicologico padre/madre', 'Desenlace'),
    ('Adiccion padre/madre', 'Desenlace'),
    ('Relaciones conflictivas hijo-padre/madre', 'Desenlace'),
    ('Familia reconstruida', 'Desenlace'),
    ('Aceptacion/rechazo parental', 'Desenlace'),
    ('Control parental', 'Desenlace')
]

BAYES_NETWORK_EDGES_PROFESSIONAL = [
    ('Curso', 'Desenlace'),
    ('Sexo asignado', 'Desenlace'),
    ('Transgenero', 'Desenlace'),
    ('Edad', 'Desenlace'),
    ('Altura', 'Desenlace'),
    ('Peso', 'Desenlace'),
    ('Madre adolescente', 'Desenlace'),
    ('Padre adolescente', 'Desenlace'),
    ('Padres divorciados', 'Desenlace'),
    ('Familia monoparental', 'Desenlace'),
    ('Tratamiento psicologico padre/madre', 'Desenlace'),
    ('Adiccion padre/madre', 'Desenlace'),
    ('Relaciones conflictivas hijo-padre/madre', 'Desenlace'),
    ('Familia reconstruida', 'Desenlace'),
    ('Situacion economica familiar precaria', 'Desenlace'),
    ('Estudios de la madre', 'Desenlace'),
    ('Estudios del padre', 'Desenlace'),
    ('Supervision parental insuficiente', 'Desenlace'),
    ('Maltrato al adolescente', 'Desenlace'),
    ('Duelo', 'Desenlace'),
    ('Ingreso familiar mensual', 'Desenlace')
]

BAYES_NETWORK_STATE_NAMES_2 = {
    'Curso':['COLEGIO', 'ESO', 'BACHILLERATO', 'UNIVERSIDAD', 'FORMACION PROFESIONAL'], 
    'Sexo asignado':['HOMBRE', 'MUJER', 'OTRO'], 
    'Transgenero':['SI','NO','NO ESTOY SEGURO DE SER TRANS', 'NO ESTOY SEGURO DE LO QUE SE PREGUNTA'], 
    'Edad':['MENOR DE 12', '12', '13', '14', '15', '16', '17', '18', '19', '20', '21', 'MAYOR DE 21'], 
    'Situacion laboral padre':['NO TRABAJA', 'TRABAJA', 'PENSIONADO'], 
    'Situacion laboral madre': ['NO TRABAJA', 'TRABAJA', 'PENSIONADO'], 
    'Nivel profesional padre':['BAJO', 'MEDIO', 'ALTO'], 
    'Nivel profesional madre':['BAJO', 'MEDIO', 'ALTO'],
    'Nivel promedio del rendimiento academico':['INSUFICIENTE', 'SUFICIENTE', 'NOTABLE', 'SOBRESALIENTE', 'EXTRAORDINARIO'],
    'Nivel de autopercepcion masculina':['0','1','2','3','4','5','6'],
    'Nivel de autopercepcion femenina':['0','1','2','3','4','5','6'],
    'Nivel de heteropercepcion masculina':['0','1','2','3','4','5','6'],
    'Nivel de heteropercepcion femenina':['0','1','2','3','4','5','6'],
    'Altura':['MENOS DE 149', '150-159', '160-169','170-179','180-189','MAS DE 190'],
    'Peso':['MENOS DE 49', '50-59', '60-69','70-79','80-89','MAS DE 90'],
    'Tratamiento psiquiatrico previo':['SI','NO'],
    'Presenta enfermedad cronica':['SI','NO'],
    'Bullying victima':['SI','NO'],
    'Bullying perpetrador':['SI','NO'],
    'Cyberbullying victima':['SI','NO'],
    'Cyberbullying perpetrador':['SI','NO'],
    'Adiccion/abuso alcohol':['SI','NO'],
    'Adiccion/abuso sustancias':['SI','NO'],
    'Adiccion/abuso Internet':['SI','NO'],
    'Problemas interiorizados':['SI','NO'],
    'Problemas exteriorizados':['SI','NO'],
    'Problemas de contexto':['SI','NO'],
    'Problemas recursos psicologicos':['SI','NO'],
    'Percepcion de discriminacion':['SI','NO'],
    'Fuente de discriminacion':['EDAD','RAZA','DISCAPACIDAD','GENERO','ORIENTACION SEXUAL'],
    'Nivel de resistencia/resiliencia':['1','2','3','4','5'],
    'Nivel de regulacion positiva':['1','2','3','4','5'],
    'Nivel de regulacion negativa':['1','2','3','4','5'],
    'Atrapamiento interno':['SI','NO'],
    'Atrapamiento externo':['SI','NO'],
    'Nivel percibido de derrota o fracaso':['BAJO','MEDIO', 'ALTO'],
    'Sentido de pertenencia frustada':['SI','NO'],
    'Percepcion de ser una carga':['SI','NO'],
    'Autoeficiencia para el suicidio':['SI', 'NO'],
    'Madre adolescente':['SI', 'NO'],
    'Padre adolescente':['SI', 'NO'],
    'Padres divorciados':['SI', 'NO'],
    'Familia monoparental':['SI', 'NO'],
    'Tratamiento psicologico padre/madre':['SI', 'NO'],
    'Adiccion padre/madre':['SI', 'NO'],
    'Relaciones conflictivas hijo-padre/madre':['SI', 'NO'],
    'Familia reconstruida':['SI', 'NO'],
    'Busqueda informacion autolesion':['SI', 'NO'],
    'Compartir en RRSS pensamiento autolesion':['SI', 'NO'],
    'Peticion ayuda en Internet':['SI', 'NO'],
    'Contagio':['SI', 'NO'], 
    'Tener conocidos que comparten autolesion en Internet':['SI', 'NO'],
    'Via de contacto para RRSS':['SI', 'NO'],
    'Contacto informacion autolesion':['SI', 'NO'],
    'Denuncia autolesion Internet':['SI', 'NO'],
    'Aceptacion/rechazo parental':['ACEPTACION', 'RECHAZO'],
    'Control parental':['SI', 'NO'],
    'Situacion economica familiar precaria':['SI', 'NO'],
    'Estudios de la madre':['SI', 'NO'],
    'Estudios del padre':['SI', 'NO'],
    'Supervision parental insuficiente':['SI', 'NO'],
    'Maltrato al adolescente':['SI', 'NO'],
    'Duelo':['SI', 'NO'],
    'Ingreso familiar mensual':['MENOS DE 499', '500-999','1000-1499','2000-2499','MAS DE 2500'],
    'Desenlace':['COMUNICACION', 'DESEO','IDEACION','PLANIFICACION','INTENCION','FINALIDAD']
}

BAYES_NETWORK_STATE_NAMES = {
        'Curso':[0,1,2,3,4],
        'Sexo asignado':[0,1,2],
        'Transgenero':[0,1,2,3],
        'Edad':[0,1,2,3,4,5,6,7,8,9,10,11],
        'Situacion laboral padre':[0,1,2],
        'Situacion laboral madre':[0,1,2],
        'Nivel profesional padre':[0,1,2],
        'Nivel profesional madre':[0,1,2],
        'Nivel promedio del rendimiento academico':[0,1,2,3,4],
        'Nivel de autopercepcion masculina':[0,1,2,3,4,5,6],
        'Nivel de autopercepcion femenina':[0,1,2,3,4,5,6],
        'Nivel de heteropercepcion masculina':[0,1,2,3,4,5,6],
        'Nivel de heteropercepcion femenina':[0,1,2,3,4,5,6],
        'Altura':[0,1,2,3,4,5],
        'Peso':[0,1,2,3,4,5],
        'Tratamiento psiquiatrico previo':[0,1],
        'Presenta enfermedad cronica':[0,1],
        'Bullying victima':[0,1],
        'Bullying perpetrador':[0,1],
        'Cyberbullying victima':[0,1],
        'Cyberbullying perpetrador':[0,1],
        'Adiccion/abuso alcohol':[0,1],
        'Adiccion/abuso sustancias':[0,1],
        'Adiccion/abuso Internet':[0,1],
        'Problemas interiorizados':[0,1],
        'Problemas exteriorizados':[0,1],
        'Problemas de contexto':[0,1],
        'Problemas recursos psicologicos':[0,1],
        'Percepcion de discriminacion':[0,1],
        'Fuente de discriminacion':[0,1,2,3,4],
        'Nivel de resistencia/resiliencia':[0,1,2,3,4],
        'Nivel de regulacion positiva':[0,1,2,3,4],
        'Nivel de regulacion negativa':[0,1,2,3,4],
        'Atrapamiento interno':[0,1],
        'Atrapamiento externo':[0,1],
        'Nivel percibido de derrota o fracaso':[0,1,2],
        'Sentido de pertenencia frustada':[0,1],
        'Percepcion de ser una carga':[0,1],
        'Autoeficiencia para el suicidio':[0,1],
        'Madre adolescente':[0,1],
        'Padre adolescente':[0,1],
        'Padres divorciados':[0,1],
        'Familia monoparental':[0,1],
        'Tratamiento psicologico padre/madre':[0,1],
        'Adiccion padre/madre':[0,1],
        'Relaciones conflictivas hijo-padre/madre':[0,1],
        'Familia reconstruida':[0,1],
        'Busqueda informacion autolesion':[0,1],
        'Compartir en RRSS pensamiento autolesion':[0,1],
        'Peticion ayuda en Internet':[0,1],
        'Contagio':[0,1],
        'Tener conocidos que comparten autolesion en Internet':[0,1],
        'Via de contacto para RRSS':[0,1],
        'Contacto informacion autolesion':[0,1],
        'Denuncia autolesion Internet':[0,1],
        'Aceptacion/rechazo parental':[0,1],
        'Control parental':[0,1],
        'Situacion economica familiar precaria':[0,1],
        'Estudios de la madre':[0,1],
        'Estudios del padre':[0,1],
        'Supervision parental insuficiente':[0,1],
        'Maltrato al adolescente':[0,1],
        'Duelo':[0,1],
        'Ingreso familiar mensual':[0,1,2,3,4],
        'Desenlace':[0,1,2,3,4,5],
}


NEW_BAYES_NETWORK_VARIABLES_AUTOINFORME = [
    'Curso', 
    'Sexo asignado', 
    'Transgenero', 
    'Edad', 
    'Situacion laboral padre', 
    'Situacion laboral madre', 
    'Nivel profesional padre', 
    'Nivel profesional madre',
    'Nivel promedio del rendimiento academico',
    'Nivel de autopercepcion masculina',
    'Nivel de autopercepcion femenina',
    'Nivel de heteropercepcion masculina',
    'Nivel de heteropercepcion femenina',
    'Altura',
    'Peso',
    'Tratamiento psiquiatrico previo',
    'Presenta enfermedad cronica',
    'Presencia pasado clinico'
    'Bullying victima',
    'Bullying perpetrador',
    'Presencia de bullying'
    'Cyberbullying victima',
    'Cyberbullying perpetrador',
    'Presencia de cyberbullying',
    'Adiccion/abuso alcohol',
    'Adiccion/abuso sustancias',
    'Adiccion/abuso Internet',
    'Presencia de adicciones',
    'Problemas interiorizados',
    'Problemas exteriorizados',
    'Problemas de contexto',
    'Problemas recursos psicologicos',
    'Presencia de problemas psicopatologicos',
    'Percepcion de discriminacion',
    'Discriminacion por edad',
    'Discriminacion por raza',
    'Discriminacion por genero',
    'Discriminacion por discapacidad',
    'Discriminacion por orientacion sexual',
    'Nivel de resistencia/resiliencia',
    'Nivel de regulacion positiva',
    'Nivel de regulacion negativa',
    'Atrapamiento interno',
    'Atrapamiento externo',
    'Presencia de atrapamiento',
    'Nivel percibido de derrota o fracaso',
    'Sentido de pertenencia frustada',
    'Percepcion de ser una carga',
    'Autoeficiencia para el suicidio',
    'Presencia de motivos para el suicidio',
    'Madre adolescente',
    'Padre adolescente',
    'Padres adolescentes',
    'Padres divorciados',
    'Familia monoparental',
    'Tratamiento psicologico padre/madre',
    'Adiccion padre/madre',
    'Relaciones conflictivas hijo-padre/madre',
    'Familia reconstruida',
    'Presencia de problemas familiares',
    'Busqueda informacion autolesion',
    'Compartir en RRSS pensamiento autolesion',
    'Peticion ayuda en Internet',
    'Contagio', 
    'Tener conocidos que comparten autolesion en Internet',
    'Via de contacto para RRSS',
    'Contacto informacion autolesion',
    'Denuncia autolesion Internet',
    'Presencia influencia de tecnologías y RRSS',
    'Desenlace'
]

NEW_BAYES_NETWORK_EDGES_AUTOINFORME = [
    ('Curso', 'Desenlace'),
    ('Sexo asignado', 'Desenlace'),
    ('Transgenero', 'Desenlace'),
    ('Edad', 'Desenlace'),
    ('Situacion laboral padre', 'Desenlace'),
    ('Situacion laboral madre', 'Desenlace'),
    ('Nivel profesional padre', 'Desenlace'),
    ('Nivel profesional madre', 'Desenlace'),
    ('Nivel promedio del rendimiento academico', 'Desenlace'),
    ('Nivel de autopercepcion masculina', 'Desenlace'),
    ('Nivel de autopercepcion femenina', 'Desenlace'),
    ('Nivel de heteropercepcion masculina', 'Desenlace'),
    ('Nivel de heteropercepcion femenina', 'Desenlace'),
    ('Altura', 'Desenlace'),
    ('Peso', 'Desenlace'),
    ('Tratamiento psiquiatrico previo', 'Presencia pasado clinico'),
    ('Presenta enfermedad cronica', 'Presencia pasado clinico'),
    ('Presencia pasado clinico', 'Desenlace'),
    ('Bullying victima', 'Presencia de bullying'),
    ('Bullying perpetrador', 'Presencia de bullying'),
    ('Cyberbullying victima', 'Presencia de cyberbullying'),
    ('Cyberbullying perpetrador', 'Presencia de cyberbullying'),
    ('Presencia de bullying', 'Desenlace'),
    ('Presencia de cyberbullying', 'Desenlace'),
    ('Adiccion/abuso alcohol', 'Presencia de adicciones'),
    ('Adiccion/abuso sustancias', 'Presencia de adicciones'),
    ('Adiccion/abuso Internet', 'Presencia de adicciones'),
    ('Presencia de adicciones', 'Desenlace'),
    ('Problemas interiorizados', 'Presencia problemas de psicopatologicos'),
    ('Problemas exteriorizados', 'Presencia problemas de psicopatologicos'),
    ('Problemas de contexto', 'Presencia problemas de psicopatologicos'),
    ('Problemas recursos psicologicos', 'Presencia problemas de psicopatologicos'),
    ('Presencia de problemas psicopatologicos', 'Desenlace'),
    ('Discriminacion por edad', 'Percepcion de discriminacion'),
    ('Discriminacion por raza', 'Percepcion de discriminacion'),
    ('Discriminacion por genero', 'Percepcion de discriminacion'),
    ('Discriminacion por discapacidad', 'Percepcion de discriminacion'),
    ('Discriminacion por orientacion sexual', 'Percepcion de discriminacion'),
    ('Percepcion de discriminacion', 'Desenlace'),
    ('Nivel de resistencia/resiliencia', 'Desenlace'),
    ('Nivel de regulacion positiva', 'Desenlace'),
    ('Nivel de regulacion negativa', 'Desenlace'),
    ('Atrapamiento interno', 'Presencia de atrapamiento'),
    ('Atrapamiento externo', 'Presencia de atrapamiento'),
    ('Presencia de atrapamiento', 'Presencia de motivos para el suicidio'),
    ('Nivel percibido de derrota o fracaso', 'Desenlace'),
    ('Sentido de pertenencia frustada', 'Presencia de motivos para el suicidio'),
    ('Percepcion de ser una carga', 'Presencia de motivos para el suicidio'),
    ('Autoeficiencia para el suicidio', 'Presencia de motivos para el suicidio'),
    ('Madre adolescente', 'Padres adolescentes'),
    ('Padre adolescente', 'Padres adolescentes'),
    ('Padres adolescentes', 'Presencia de problemas familiares'),
    ('Padres divorciados', 'Presencia de problemas familiares'),
    ('Familia monoparental', 'Presencia de problemas familiares'),
    ('Tratamiento psicologico padre/madre', 'Presencia de problemas familiares'),
    ('Adiccion padre/madre', 'Presencia de problemas familiares'),
    ('Relaciones conflictivas hijo-padre/madre', 'Presencia de problemas familiares'),
    ('Familia reconstruida', 'Presencia de problemas familiares'),
    ('Busqueda informacion autolesion', 'Presencia de influencia de tecnologias y RRSS'),
    ('Compartir en RRSS pensamiento autolesion', 'Presencia de influencia de tecnologias y RRSS'),
    ('Peticion ayuda en Internet', 'Presencia de influencia de tecnologias y RRSS'),
    ('Contagio', 'Presencia de influencia de tecnologias y RRSS'),
    ('Tener conocidos que comparten autolesion en Internet', 'Presencia de influencia de tecnologias y RRSS'),
    ('Via de contacto para RRSS', 'Presencia de influencia de tecnologias y RRSS'),
    ('Contacto informacion autolesion', 'Presencia de influencia de tecnologias y RRSS'),
    ('Denuncia autolesion Internet', 'Presencia de influencia de tecnologias y RRSS'),
    ('Presencia de influencia de tecnologias y RRSS', 'Desenlace')
]

BAYES_NETWORK_STATE_NAMES_3 = {
    'Curso':['COLEGIO', 'ESO', 'BACHILLERATO', 'UNIVERSIDAD', 'FORMACION PROFESIONAL'], 
    'Sexo asignado':['HOMBRE', 'MUJER', 'OTRO'], 
    'Transgenero':['SI','NO','NO ESTOY SEGURO DE SER TRANS', 'NO ESTOY SEGURO DE LO QUE SE PREGUNTA'], 
    'Edad':['MENOR DE 12', '12-21', 'MAYOR DE 21'], 
    'Situacion laboral padre':['NO TRABAJA', 'TRABAJA', 'PENSIONADO'], 
    'Situacion laboral madre': ['NO TRABAJA', 'TRABAJA', 'PENSIONADO'], 
    'Nivel profesional padre':['BAJO', 'MEDIO', 'ALTO'], 
    'Nivel profesional madre':['BAJO', 'MEDIO', 'ALTO'],
    'Nivel promedio del rendimiento academico':['INSUFICIENTE', 'SUFICIENTE', 'NOTABLE', 'SOBRESALIENTE', 'EXTRAORDINARIO'],
    'Nivel de autopercepcion masculina':['0','1','2','3','4','5','6'],
    'Nivel de autopercepcion femenina':['0','1','2','3','4','5','6'],
    'Nivel de heteropercepcion masculina':['0','1','2','3','4','5','6'],
    'Nivel de heteropercepcion femenina':['0','1','2','3','4','5','6'],
    'Altura':['MENOS DE 149', '150-159', '160-169','170-179','180-189','MAS DE 190'],
    'Peso':['MENOS DE 49', '50-59', '60-69','70-79','80-89','MAS DE 90'],
    'Tratamiento psiquiatrico previo':['SI','NO'],
    'Presenta enfermedad cronica':['SI','NO'],
    'Presencia pasado clinico':['SI','NO'],
    'Bullying victima':['SI','NO'],
    'Bullying perpetrador':['SI','NO'],
    'Presencia de bullying':['SI','NO'],
    'Cyberbullying victima':['SI','NO'],
    'Cyberbullying perpetrador':['SI','NO'],
    'Presencia de cyberbullying':['SI','NO'],
    'Adiccion/abuso alcohol':['SI','NO'],
    'Adiccion/abuso sustancias':['SI','NO'],
    'Adiccion/abuso Internet':['SI','NO'],
    'Presencia de adicciones':['SI','NO'],
    'Problemas interiorizados':['SI','NO'],
    'Problemas exteriorizados':['SI','NO'],
    'Problemas de contexto':['SI','NO'],
    'Problemas recursos psicologicos':['SI','NO'],
    'Presencia de problemas psicopatologicos':['SI','NO'],
    'Percepcion de discriminacion':['SI','NO'],
    'Discriminacion por edad':['SI','NO'],
    'Discriminacion por raza':['SI','NO'],
    'Discriminacion por genero':['SI','NO'],
    'Discriminacion por discapacidad':['SI','NO'],
    'Discriminacion por orientacion sexual':['SI','NO'],
    'Nivel de resistencia/resiliencia':['1','2','3','4','5'],
    'Nivel de regulacion positiva':['1','2','3','4','5'],
    'Nivel de regulacion negativa':['1','2','3','4','5'],
    'Atrapamiento interno':['SI','NO'],
    'Atrapamiento externo':['SI','NO'],
    'Presencia de atrapamiento':['SI','NO'],
    'Nivel percibido de derrota o fracaso':['BAJO','MEDIO', 'ALTO'],
    'Sentido de pertenencia frustada':['SI','NO'],
    'Percepcion de ser una carga':['SI','NO'],
    'Autoeficiencia para el suicidio':['SI', 'NO'],
    'Presencia de motivos para el suicidio':['SI','NO'],
    'Madre adolescente':['SI', 'NO'],
    'Padre adolescente':['SI', 'NO'],
    'Padres adolescentes':['SI','NO'],
    'Padres divorciados':['SI', 'NO'],
    'Familia monoparental':['SI', 'NO'],
    'Tratamiento psicologico padre/madre':['SI', 'NO'],
    'Adiccion padre/madre':['SI', 'NO'],
    'Relaciones conflictivas hijo-padre/madre':['SI', 'NO'],
    'Familia reconstruida':['SI', 'NO'],
    'Presencia de problemas familiares':['SI','NO'],
    'Busqueda informacion autolesion':['SI', 'NO'],
    'Compartir en RRSS pensamiento autolesion':['SI', 'NO'],
    'Peticion ayuda en Internet':['SI', 'NO'],
    'Contagio':['SI', 'NO'], 
    'Tener conocidos que comparten autolesion en Internet':['SI', 'NO'],
    'Via de contacto para RRSS':['SI', 'NO'],
    'Contacto informacion autolesion':['SI', 'NO'],
    'Denuncia autolesion Internet':['SI', 'NO'],
    'Presencia influencia de tecnologías y RRSS':['SI','NO'],
    'Aceptacion parental':['SI', 'NO'],
    'Control parental':['SI', 'NO'],
    'Influencia parental':['SI','NO'],
    'Situacion economica familiar precaria':['SI', 'NO'],
    'Estudios de la madre':['SI', 'NO'],
    'Estudios del padre':['SI', 'NO'],
    'Estudios de los padres':['SI', 'NO'],
    'Supervision parental insuficiente':['SI', 'NO'],
    'Maltrato al adolescente':['SI', 'NO'],
    'Duelo':['SI', 'NO'],
    'Presencia influencia de los padres':['SI', 'NO'],
    'Ingreso familiar mensual':['MENOS DE 499', '500-999','1000-1499','2000-2499','MAS DE 2500'],
    'Desenlace':['COMUNICACION', 'DESEO','IDEACION','PLANIFICACION','INTENCION','FINALIDAD']
}

BAYES_NETWORK_STATE_NAMES_3_2 = {
    'Curso':['COLEGIO', 'ESO', 'BACHILLERATO', 'UNIVERSIDAD', 'FORMACION PROFESIONAL'], 
    'Sexo asignado':['HOMBRE', 'MUJER', 'OTRO'], 
    'Transgenero':['SI','NO','NO ESTOY SEGURO DE SER TRANS', 'NO ESTOY SEGURO DE LO QUE SE PREGUNTA'], 
    'Edad':['MENOR DE 12', '12-21', 'MAYOR DE 21'], 
    'Situacion laboral padre':['NO TRABAJA', 'TRABAJA', 'PENSIONADO'], 
    'Situacion laboral madre': ['NO TRABAJA', 'TRABAJA', 'PENSIONADO'], 
    'Nivel profesional padre':['BAJO', 'MEDIO', 'ALTO'], 
    'Nivel profesional madre':['BAJO', 'MEDIO', 'ALTO'],
    'Nivel promedio del rendimiento academico':['INSUFICIENTE', 'SUFICIENTE', 'NOTABLE', 'SOBRESALIENTE', 'EXTRAORDINARIO'],
    'Nivel de autopercepcion masculina':['0','1','2','3','4','5','6'],
    'Nivel de autopercepcion femenina':['0','1','2','3','4','5','6'],
    'Nivel de heteropercepcion masculina':['0','1','2','3','4','5','6'],
    'Nivel de heteropercepcion femenina':['0','1','2','3','4','5','6'],
    'Altura':['MENOS DE 149', '150-159', '160-169','170-179','180-189','MAS DE 190'],
    'Peso':['MENOS DE 49', '50-59', '60-69','70-79','80-89','MAS DE 90'],
    'Tratamiento psiquiatrico previo':['SI','NO'],
    'Presenta enfermedad cronica':['SI','NO'],
    'Presencia pasado clinico':['SI','NO'],
    'Bullying victima':['SI','NO'],
    'Bullying perpetrador':['SI','NO'],
    'Presencia de bullying':['SI','NO'],
    'Cyberbullying victima':['SI','NO'],
    'Cyberbullying perpetrador':['SI','NO'],
    'Presencia de cyberbullying':['SI','NO'],
    'Adiccion/abuso alcohol':['SI','NO'],
    'Adiccion/abuso sustancias':['SI','NO'],
    'Adiccion/abuso Internet':['SI','NO'],
    'Presencia de adicciones':['SI','NO'],
    'Problemas interiorizados':['SI','NO'],
    'Problemas exteriorizados':['SI','NO'],
    'Problemas de contexto':['SI','NO'],
    'Problemas recursos psicologicos':['SI','NO'],
    'Presencia de problemas psicopatologicos':['SI','NO'],
    'Percepcion de discriminacion':['SI', 'NO'],
    'Fuente de discriminacion':['EDAD','RAZA', 'GENERO', 'DISCAPACIDAD', 'ORIENTACION SEXUAL'],
    'Nivel de resistencia/resiliencia':['1','2','3','4','5'],
    'Nivel de regulacion positiva':['1','2','3','4','5'],
    'Nivel de regulacion negativa':['1','2','3','4','5'],
    'Atrapamiento interno':['SI','NO'],
    'Atrapamiento externo':['SI','NO'],
    'Presencia de atrapamiento':['SI','NO'],
    'Nivel percibido de derrota o fracaso':['BAJO','MEDIO', 'ALTO'],
    'Sentido de pertenencia frustada':['SI','NO'],
    'Percepcion de ser una carga':['SI','NO'],
    'Autoeficiencia para el suicidio':['SI', 'NO'],
    'Presencia de motivos para el suicidio':['SI','NO'],
    'Madre adolescente':['SI', 'NO'],
    'Padre adolescente':['SI', 'NO'],
    'Padres adolescentes':['SI','NO'],
    'Padres divorciados':['SI', 'NO'],
    'Familia monoparental':['SI', 'NO'],
    'Tratamiento psicologico padre/madre':['SI', 'NO'],
    'Adiccion padre/madre':['SI', 'NO'],
    'Relaciones conflictivas hijo-padre/madre':['SI', 'NO'],
    'Familia reconstruida':['SI', 'NO'],
    'Presencia de problemas familiares':['SI','NO'],
    'Busqueda informacion autolesion':['SI', 'NO'],
    'Compartir en RRSS pensamiento autolesion':['SI', 'NO'],
    'Peticion ayuda en Internet':['SI', 'NO'],
    'Contagio':['SI', 'NO'], 
    'Tener conocidos que comparten autolesion en Internet':['SI', 'NO'],
    'Via de contacto para RRSS':['SI', 'NO'],
    'Contacto informacion autolesion':['SI', 'NO'],
    'Denuncia autolesion Internet':['SI', 'NO'],
    'Presencia influencia de tecnologías y RRSS':['SI','NO'],
    'Aceptacion parental':['SI', 'NO'],
    'Control parental':['SI', 'NO'],
    'Influencia parental':['SI','NO'],
    'Situacion economica familiar precaria':['SI', 'NO'],
    'Estudios de la madre':['SI', 'NO'],
    'Estudios del padre':['SI', 'NO'],
    'Estudios de los padres':['SI', 'NO'],
    'Supervision parental insuficiente':['SI', 'NO'],
    'Maltrato al adolescente':['SI', 'NO'],
    'Duelo':['SI', 'NO'],
    'Presencia influencia de los padres':['SI', 'NO'],
    'Ingreso familiar mensual':['MENOS DE 499', '500-999','1000-1499','2000-2499','MAS DE 2500'],
    'Desenlace':['COMUNICACION', 'DESEO','IDEACION','PLANIFICACION','INTENCION','FINALIDAD']
}



BAYES_NETWORK_STATE_NAMES_3_1 = {
        'Curso':[0,1,2,3,4],
        'Sexo asignado':[0,1,2],
        'Transgenero':[0,1,2,3],
        'Edad':[0,1,2],
        'Situacion laboral padre':[0,1,2],
        'Situacion laboral madre':[0,1,2],
        'Nivel profesional padre':[0,1,2],
        'Nivel profesional madre':[0,1,2],
        'Nivel promedio del rendimiento academico':[0,1,2,3,4],
        'Nivel de autopercepcion masculina':[0,1,2,3,4,5,6],
        'Nivel de autopercepcion femenina':[0,1,2,3,4,5,6],
        'Nivel de heteropercepcion masculina':[0,1,2,3,4,5,6],
        'Nivel de heteropercepcion femenina':[0,1,2,3,4,5,6],
        'Altura':[0,1,2,3,4,5],
        'Peso':[0,1,2,3,4,5],
        'Tratamiento psiquiatrico previo':[0,1],
        'Presenta enfermedad cronica':[0,1],
        'Bullying victima':[0,1],
        'Bullying perpetrador':[0,1],
        'Cyberbullying victima':[0,1],
        'Cyberbullying perpetrador':[0,1],
        'Adiccion/abuso alcohol':[0,1],
        'Adiccion/abuso sustancias':[0,1],
        'Adiccion/abuso Internet':[0,1],
        'Problemas interiorizados':[0,1],
        'Problemas exteriorizados':[0,1],
        'Problemas de contexto':[0,1],
        'Problemas recursos psicologicos':[0,1],
        'Percepcion de discriminacion':[0,1],
        'Fuente de discriminacion':[0,1,2,3,4],
        'Nivel de resistencia/resiliencia':[0,1,2,3,4],
        'Nivel de regulacion positiva':[0,1,2,3,4],
        'Nivel de regulacion negativa':[0,1,2,3,4],
        'Atrapamiento interno':[0,1],
        'Atrapamiento externo':[0,1],
        'Nivel percibido de derrota o fracaso':[0,1,2],
        'Sentido de pertenencia frustada':[0,1],
        'Percepcion de ser una carga':[0,1],
        'Autoeficiencia para el suicidio':[0,1],
        'Madre adolescente':[0,1],
        'Padre adolescente':[0,1],
        'Padres divorciados':[0,1],
        'Familia monoparental':[0,1],
        'Tratamiento psicologico padre/madre':[0,1],
        'Adiccion padre/madre':[0,1],
        'Relaciones conflictivas hijo-padre/madre':[0,1],
        'Familia reconstruida':[0,1],
        'Busqueda informacion autolesion':[0,1],
        'Compartir en RRSS pensamiento autolesion':[0,1],
        'Peticion ayuda en Internet':[0,1],
        'Contagio':[0,1],
        'Tener conocidos que comparten autolesion en Internet':[0,1],
        'Via de contacto para RRSS':[0,1],
        'Contacto informacion autolesion':[0,1],
        'Denuncia autolesion Internet':[0,1],
        'Aceptacion/rechazo parental':[0,1],
        'Control parental':[0,1],
        'Situacion economica familiar precaria':[0,1],
        'Estudios de la madre':[0,1],
        'Estudios del padre':[0,1],
        'Supervision parental insuficiente':[0,1],
        'Maltrato al adolescente':[0,1],
        'Duelo':[0,1],
        'Ingreso familiar mensual':[0,1,2,3,4],
        'Desenlace':[0,1,2,3,4,5],
}